### ISSUE TITLE
Feature Request: Add support for the default Querydsl annotation processor that supports @QueryEntity

### ISSUE THREAD

**Issue by griffio** [ewerk/gradle-plugins#1]
Could the below feature be considered useful for this plugin?

In version 1.0.1 there is no plugin support for accessing the default "com.mysema.query.apt.QuerydslAnnotationProcessor" that generates models for @QueryEntity

e.g.
```java
@QueryEntity
public class Issue {
}
```

The build.gradle task could have an explict option for that annotation processor

e.g.
```groovy
querydsl {
 querydsl = true
 jpa = true
}
```

I could try and submit a Pull Request for the changes but wanted to check if you had wanted to include this feature at all first. Thanks.

**Comment by holgerstolzenberg** [comment]
That sounds like a reasonable addition. Adding it should not be too complicated. When do you think you can provide the PR? Otherwise it would be just a small change to add it by myself.

**Comment by griffio** [comment]
I would be able to provide PR by end of this week as now travelling for next 24hrs.
The plugin is very useful , if you have the time to make the change before I get back then that would be great too.

**Comment by holgerstolzenberg** [comment]
It would be nice if you could provide a PR. I´d like to have more contributors within the project.

**Comment by griffio** [comment]
I have pushed the PR as branch issue1.
Changed the core plugin only.
Once the plugin is published then the ReadMe and sample application can be updated.
I tested locally by using the snapshot version of the plugin in the sample application project as below.

```groovy
buildscript {
  repositories {
    mavenLocal()
  }

  dependencies {
    classpath "com.ewerk.gradle.plugins:querydsl-plugin:1.0.2-SNAPSHOT"
  }

}

plugins {
  id "java"
  id "com.ewerk.gradle.plugins.auto-value" version "1.0.1"
  id "com.ewerk.gradle.plugins.integration-test" version "1.0.6"
}

apply plugin: "com.ewerk.gradle.plugins.querydsl"
```

**Comment by holgerstolzenberg** [comment]
Plugin was released and is available via http://plugins.gradle.org. Sample application has been updated. Global README contains new hint pointing to sample application.
