### ISSUE TITLE
querydsl-plugin don't work in Gradle 5.0

### ISSUE THREAD

**Issue by marcomsousa** [ewerk/gradle-plugins#108]
I use querydsl-plugin-1.0.10, when I change Gradle 4.10 to 5.0 stop working.

```
10:21:55.485 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
10:21:55.485 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
10:21:55.485 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
10:21:55.485 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':compileQuerydsl'.
10:21:55.485 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Annotation processor 'org.springframework.data.mongodb.repository.support.MongoAnnotationProcessor' not found
```

**Comment by griffio** [comment]
Hi @marcomsousa 

Currently this plugin is unlikely to work with Gradle 5.x as there are a number of internal changes required from Gradle 4.6 needed to support the upcoming release.

I tried with the latest release candidate version

`./gradlew wrapper --gradle-version=5.0-rc-4
`
and confirm error with

`./gradlew --S build
` 

I believe that Gradle 5 doesn't load annotation processors from the compile classpath anymore.
The current plugin will have to be re-organized to work against Gradle 5.

**Comment by marcomsousa** [comment]
I don't know if this can help you, but with gradle 5.0 we have to change in the dependencies block, from 

` apt("org.mapstruct:mapstruct-processor:${mapstructVersion}")`
to
` annotationProcessor("org.mapstruct:mapstruct-processor:${mapstructVersion}")`

**Comment by kmaterka** [comment]
As a workaround add:

```
compileQuerydsl {
    options.annotationProcessorPath = configurations.querydsl
}
```

**Comment by holgerstolzenberg** [comment]
The plugins are not compatible to Gradle 5 at the moment.

**Comment by SayakMukhopadhyay** [comment]
Any ETA for the fix of this issue?

**Comment by feanor777** [comment]
> As a workaround add:
> 
> ```
> compileQuerydsl {
>     options.annotationProcessorPath = configurations.querydsl
> }
> ```
Thanks, it works.
But are there a normal solution, without extra settings?

**Comment by unikzforce** [comment]
this problem seems to be serious. and  also
```compileQuerydsl {
    options.annotationProcessorPath = configurations.querydsl
}
```
didn't work.

**Comment by holgerstolzenberg** [comment]
Closing in favour of #116.

**Comment by darshanmehta10** [comment]
@kmaterka I am having the same problem and tried to add `compileQuerydsl` block. However, I got another error saying:
```
org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method compileQuerydsl() for arguments [build_34f65uphys3x3neud0s7h85bz$_run_closure1$_closure14@47966d1f] on root project 'my-project' of type org.gradle.api.Project
```

Where exactly do we need to add this block?

**Comment by kmaterka** [comment]
@darshanmehta10 

I'm no longer using this plugin, with latest Gradle it is not needed. My configuration:

```groovy
plugins {
    id 'java-library'
}

configurations {
    annotationProcessor.extendsFrom implementation
}

dependencies {
    annotationProcessor "com.querydsl:querydsl-apt:${querydslVersion}:jpa"

    api 'org.hibernate.validator:hibernate-validator'
    api 'com.querydsl:querydsl-jpa'
    // other dependencies...
}
```

**Comment by digz6666** [comment]
> @darshanmehta10
> 
> I'm no longer using this plugin, with latest Gradle it is not needed. My configuration:
> 
> ```groovy
> plugins {
>     id 'java-library'
> }
> 
> configurations {
>     annotationProcessor.extendsFrom implementation
> }
> 
> dependencies {
>     annotationProcessor "com.querydsl:querydsl-apt:${querydslVersion}:jpa"
> 
>     api 'org.hibernate.validator:hibernate-validator'
>     api 'com.querydsl:querydsl-jpa'
>     // other dependencies...
> }
> ```

How about mongodb?

**Comment by kmaterka** [comment]
> > @darshanmehta10
> How about mongodb?

Never used that...

Start with something like:
`annotationProcessor "org.springframework.data:spring-data-mongodb"`

**Comment by unikzforce** [comment]
in this repository [interview](https://github.com/unikzforce/interview) i've used gradle 6.5 and ewerk plugin 1.0.10

It's not a complete project.

So It can be only build by `./gradlew clean build -x test`

I have a `Dog` class and It seems that It has added `QDog` class for me successfully.
I Cannot confirm this completely right now, but as I continue my task I'll know.
So I'll let you guys know.

**Comment by unikzforce** [comment]
Don't know why it's not working well with `implementation`, It's only working with `compile`

**Comment by digz6666** [comment]
> Don't know why it's not working well with `implementation`, It's only working with `compile`

Seems like it needs to be updated with newest gradle.
