### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by k1per** [ewerk/gradle-plugins#109]
By adding kotlin plugin (org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.10) and trying to build project with jaxb2 plugin getting weird exception

Task with name 'compileJaxb2Kotlin' not found in project

problem occurs when using kotlin plugin verstion 1.3.10, but okay for 1.2.30

**Comment by holgerstolzenberg** [comment]
The plugin is not intended nor designed to be used with Kotlin
