### ISSUE TITLE
Should we delete Bintray account as it is no more needed due to new publication process

### ISSUE THREAD

**Issue by holgerstolzenberg** [ewerk/gradle-plugins#11]
Do not forget to notify users if deletion will take place.

**Comment by holgerstolzenberg** [comment]
@mkhl @normanpohl What do you think?

**Comment by mkhl** [comment]
I’m in favour of deleting the account.

**Comment by holgerstolzenberg** [comment]
Bintray account was completely deleted and README states that the plugins are now directly hosted at the plugin portal.
