### ISSUE TITLE
Upgrade querydsl-plugin to Gradle 5+

### ISSUE THREAD

**Issue by holgerstolzenberg** [ewerk/gradle-plugins#117]

**Comment by bsamartins** [comment]
@holgerstolzenberg what is the status on this? I can pick this up if needed

**Comment by holgerstolzenberg** [comment]
Hey @bsamartins,

help is pretty much appreciated. I already started with this but have no real time to finish up.
For the new "generation" of the plugins, I decided to split them out into distinct projects to have them decoupled from each other.

The source code for the new querydsl-plugin is here:
https://github.com/ewerk/querydsl-plugin

I already cleaned up some stuff, Gradle 5 is working but wanted to overhaul the plugin in general to have a clean blueprint for the other plugins.

Therefore I wanted to apply the best practices from the Gradle plugin development guides that are available now:
* https://guides.gradle.org/designing-gradle-plugins/
* https://guides.gradle.org/implementing-gradle-plugins/
* …

Feel free to go on in the new project!

**Comment by bsamartins** [comment]
No problem. 
Sorry anyway as I only gome some time now to pick this up.

Any thoughts on the following?

1. Migrate unit tests to junit jupiter
2. Migrate gradle buildscripts from groovy to the kotlin DSL

**Comment by holgerstolzenberg** [comment]
No problem to go with Jupiter. 

For Kotlin I´d say no as there is we have no in-house knowledge. What are the benefits of using Kotlin as build DSL?

**Comment by bsamartins** [comment]
There's not nothing that you couldn't do with the Groovy DSL apart from being statically compiled and better IDE integration, particularly with IntelliJ, with code completion, navigation to sources, documentation, refactorings, etc.

There are more details here
https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:ide_support

It's slightly more verbose and seems like latest version of IntelliJ seems to add some code insight improvements.

You can see how the current buildscripts look like in
https://github.com/bsamartins/querydsl-plugin/tree/gradle-kotlin-dsl

**Comment by holgerstolzenberg** [comment]
Alright. I am fine with that. You can go with Kotlin.

**Comment by bsamartins** [comment]
What is meant to be minimum JDK version required to run the plugin?
Source and target compatibility seem to target JDK 1.9 but sweeney seems to be expecting minimum 1.8.

Is it worth closing this issue and opening a new under the new project?

**Comment by holgerstolzenberg** [comment]
Well that is a good question. The old Gradle plugins are compatible with 1.8 already. On the one hand I am thinking about a more radical approach, having the new plugins being compatible to Java 9+ and Gradle 5, especially with the EOL of Java 1.8 in mind. Still, there might be a lot of people out there with 1.8.

I tend to say we go with 1.9, but I´d like to hear your opinion on that.

The inconsistency between target and sweeney has to be addressed tough afterwards.

I think we can open up a new issue under the new project, link it here and close this one.

**Comment by bsamartins** [comment]
Although, I too favor big bangs, at the moment I don't see a need to move into 1.9 or later, since 1.8 seems to be the minimum required for most projects.

Targeting 1.8 will give teams/developers the opportunity to keep using the plugin with Gradle (which still requires at least java 8)  without forcing them to make the move to a later JDK.

**Comment by holgerstolzenberg** [comment]
Okay then we go with 1.8

**Comment by holgerstolzenberg** [comment]
Closing in favour of https://github.com/ewerk/querydsl-plugin/issues/3
