### ISSUE TITLE
Upgrade annotation-processor plugin to Gradle 5+

### ISSUE THREAD

**Issue by holgerstolzenberg** [ewerk/gradle-plugins#118]

**Comment by bsamartins** [comment]
@holgerstolzenberg what is the status on this? I can pick this up if needed

**Comment by holgerstolzenberg** [comment]
@bsamartins I completely missed your comment on this one. Are you still willing to port the plugin?

**Comment by badgolim** [comment]
Is there some workaround to use gradle 5 and query dsl?

**Comment by holgerstolzenberg** [comment]
There is an incubating plugin not yet released: https://github.com/ewerk/querydsl-plugin

But as of Gradle 5 no specific plugin is necessary because Gradle annotation processing supports that out of the box.
