### ISSUE TITLE
Problem using querydsl-plugin with gradle plugin for checkstyle

### ISSUE THREAD

**Issue by bernadeteaquino** [ewerk/gradle-plugins#12]
When I run the command 'gradle build', compilation error occurs in the task 'compileQuerydslJava'. The error reports that the package 'com.mysema.query.types' does not exist. However, this package is on the classpath. This error occurs when using the plugin 'querydsl-plugin' with the gradle plugin for checkstyle. Even with the error, Q* classes are generated. The command output is as follows:
```
gradle build 

:initQuerydslSourcesDir
:compileQuerydsl UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar
:bootRepackage
:assemble
:checkstyleMain UP-TO-DATE
:compileQuerydslJava
/home/user/workspaces/YouKnow/youknow/Code/youknow-rest-ng/src/querydsl/java/net/afferolab/youknow/domain/QOrganization.java:3: error: package com.mysema.query.types does not exist
import static com.mysema.query.types.PathMetadataFactory.*;
```

Do you know what I should do?

**Comment by griffio** [comment]
You can set the checkstyle plugin sourceSets configuration to just use the "main" source set and not execute the querydsl sourceset task. 

So, please try adding the following to your build file.

~~~ groovy
checkstyle {
  sourceSets = [sourceSets.main]
}
~~~

---

The problem is the task "compileQuerydslJava" that is created by the JavaPlugin and is being executed by the checkstyle plugin by default.

**Comment by holgerstolzenberg** [comment]
@bernadeteaquino Is that okay for you?

**Comment by holgerstolzenberg** [comment]
If there is no new information about this, I will close this ticket. @griffio What do you think?

**Comment by griffio** [comment]
Yes. Perhaps a simple checkstyle config can be applied to the sample applications to show it plays nice.

**Comment by holgerstolzenberg** [comment]
Good idea. Will go for it.

**Comment by bernadeteaquino** [comment]
It worked, thanks! @griffio @holgerstolzenberg

**Comment by holgerstolzenberg** [comment]
Without any further detailed information we cannot suggest solutions. Please be more precise what you did and what does not work. Maybe it is a good idea to open up a new issue concluding the `build.gradle` that does not work.

**Comment by gandrade** [comment]
Yeap, this workaround still works for the most recent plugin version; Currently using `1.0.10` version.
