### ISSUE TITLE
Upgrade jaxb2-plugin to Gradle 5+

### ISSUE THREAD

**Issue by holgerstolzenberg** [ewerk/gradle-plugins#121]

**Comment by deepy** [comment]
Is this still an issue?

We're running it on Gradle 5.6.4 and I'm not seeing any warnings related to the jaxb2-plugin.

**Comment by holgerstolzenberg** [comment]
The idea is to modernize the plugin. Still, as of Gradle 5 annotation processor handling has become more easy, so that plugin itself is kinda obsolete. At the moment I am unsure whether to continue the plugin.
