### ISSUE TITLE
 Annotation processor '' not found

### ISSUE THREAD

**Issue by ankitkeer** [ewerk/gradle-plugins#123]
_I get the below error when I included the querydsl plugin in my build file._

---------------------------------------------------------------------------------------------------------
> Task :myProject:initQuerydslSourcesDir

> Task :myProject:compileQuerydsl FAILED
error: Annotation processor '' not found
warning: Annotation processing without compilation requested but no processors were found.
1 error
1 warning

---------------------------------------------------------------------------------------------------------

_**My gradle version is below:**_

------------------------------------------------------------
Gradle 5.3
------------------------------------------------------------

Build time:   2019-03-20 11:03:29 UTC
Revision:     f5c64796748a98efdbf6f99f44b6afe08492c2a0

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Windows 10 10.0 amd64

_**build.gradle**_

---------------------------------------------------------------------------------------------------------
plugins {
    id 'org.springframework.boot' version '2.1.4.RELEASE'
    id "com.ewerk.gradle.plugins.querydsl" version "1.0.10"
}

repositories {
    mavenCentral()
}

apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group = 'com.xxx.xxx'
version = rootProject.version

sourceCompatibility = 1.8

dependencies {
    implementation project(path: ':xxx-data-model')
	implementation 'org.apache.commons:commons-lang3:3.6'
    implementation 'org.reflections:reflections:0.9.11'
    implementation 'com.voodoodyne.jackson.jsog:jackson-jsog:1.1.1'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-rest'
    implementation 'org.springframework.boot:spring-boot-devtools'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.keycloak:keycloak-spring-boot-starter'
    implementation 'org.keycloak:keycloak-spring-security-adapter'
	implementation 'com.auth0:java-jwt:3.8.0'

    
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation "com.h2database:h2"

    providedRuntime 'org.springframework.boot:spring-boot-starter-undertow'
    providedCompile project(':xxx-data-model')
    providedCompile project(':xxxx-common')
}

dependencyManagement {
    imports {
        mavenBom "org.keycloak.bom:keycloak-adapter-bom:${versions.keycloak}"
    }
}

-------------------------------------------------------------------------------------------------------

**Comment by holgerstolzenberg** [comment]
The plugins are, as stated in the README not compatible to Gradle 5+. Please see https://github.com/ewerk/querydsl-plugin for an upcoming Gradle 5 compatible version!
