### ISSUE TITLE
compileQuerydslKotlin, compileQuerydslJava, processQuerydslResources NO-SOURCE

### ISSUE THREAD

**Issue by Morons** [ewerk/gradle-plugins#127]
What is needed to add - I thought it will find the SOURCES with `springDataMongo = true` and Classes annotated with `@Document`

Using /usr/lib/jvm/java-11-openjdk-amd64 (11.0.3)

gradle.wrapper.properties

`distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip`

```
plugins {
	id("com.ewerk.gradle.plugins.querydsl") version "1.0.10"
...
dependencies {
	implementation("org.springframework.boot:spring-boot-starter-data-mongodb")

	// use Querydsl against MongoDB
	implementation("com.querydsl:querydsl-mongodb:4.1.4")
}
querydsl {
	springDataMongo = true
}
```
Results in:
```
12:47:14: Executing task 'querydslClasses'...

> Task :compileQuerydslKotlin NO-SOURCE
> Task :compileQuerydslJava NO-SOURCE
> Task :processQuerydslResources NO-SOURCE
> Task :querydslClasses UP-TO-DATE

BUILD SUCCESSFUL in 297ms
12:47:14: Task execution finished 'querydslClasses'.
```

**Comment by holgerstolzenberg** [comment]
Please be more specific on your actual issue. Also please note that the plugins are not compatible with Gradle 5 and have not been implemented against JDK-8+. There is a new plugin in the making that should achieve this.

https://github.com/ewerk/querydsl-plugin
