### ISSUE TITLE
Jaxb2 plugin - Multiple schema files 

### ISSUE THREAD

**Issue by ronipolus** [ewerk/gradle-plugins#129]
Hello, 
I am trying to generate jaxb2 classes from the following xsd structure. Although, your jaxb2-plugin sets a limit to only selecting a single schema file and package name has to be specified.

The following project is a valid xjc task to generated java classes.

Would it be possible to get something similar into this plugin ? 
We would only provide the schema directory, and the bindings directory.

```
├── original.xsd
├── original-extended.xsd
├── other.xsd
├── binding.xjb
├── otherXSDs
|   ├── xsd1.xsd
|   └── xsd2.xsd
```
```
<jxb:bindings 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
    version="2.1">

   <!-- Raise theEnumMemberSizeCap limit -->
   <jxb:bindings >
       <jxb:globalBindings typesafeEnumMaxMembers="2000"/>
   </jxb:bindings>

  <jxb:bindings schemaLocation="original.xsd">
    <jxb:schemaBindings>
        <jxb:package name="org.original"/>
     </jxb:schemaBindings>
  </jxb:bindings>

<!-- This is an extension of original.xsd, it should only generated the extended classes -->
 <jxb:bindings schemaLocation="original-extended.xsd">
     <jxb:schemaBindings>
         <jxb:package name="com.sample.extended"/>
     </jxb:schemaBindings>
 </jxb:bindings>

    <jxb:bindings schemaLocation="other.xsd">
      <jxb:schemaBindings>
          <jxb:package name="com.other"/>
       </jxb:schemaBindings>
    </jxb:bindings>

</jxb:bindings>
```

The above should result in something similar to this structure:
```
├── org.original
|   ├── originalClass1.xsd
|   └── originalClassX.xsd
├── com.sample.extended
|   ├── onlyExtendedClasses1.xsd
|   └── onlyExtendedClassesX.xsd
├── com.other
|   ├── otherPackage1
|   |   ├── otherPackage1Class1.xsd
|   ├── otherPackage2
|   |   ├── otherPackage2Class1.xsd
```

Maven Jaxb2 plugin provides that capability - https://github.com/highsource/maven-jaxb2-plugin
A resource that might be useful - https://gdpotter.com/2017/08/14/jaxb-gradle-config/ 

Thank you

**Comment by holgerstolzenberg** [comment]
The plugin already supports generation from of multiple schemas as described in the plugins documentation. I didn´t work on the plugin for a long time and need to remember JAXB specific stuff.
Can you please elaborate in more detail why the current configuration for multiple schemas does not work for you?

**Comment by holgerstolzenberg** [comment]
Or can you provide a small example project that show cases the problem.
