### ISSUE TITLE
New Plugin to support Dagger2?

### ISSUE THREAD

**Issue by griffio** [ewerk/gradle-plugins#13]
Any thoughts on adding Dagger2 to your gradle-plugins collection?

The [Dagger2](http://google.github.io/dagger/) project -"Generates code that mimics the code that a user might have hand-written to ensure that dependency injection is a simple, traceable and performant as it can be."

Dagger2 has been released for a couple months now, I have had a look and think I can push something similar to the QueryDsl plugin as a "configuration" is needed for the processor "com.google.dagger:dagger-compiler" and a library dependency "com.google.dagger:dagger" for client code.

I wanted to ask first before creating a big pull request.

Regards,  

Griffio

**Comment by holgerstolzenberg** [comment]
I´d really like to get this one going. Even not having used the Dagger framework so far, why not having a plugin ready when the time comes.

I really appreciate your participation. Seems like it is getting a real open source project now :-)

Build up your PR, I think it should be a separate Plugin (named dagger-plugin). Plugin ID should be `com.ewerk.gradle.plugins.dagger`.

If possible, please also provide the readme.md and changelog.md according to the other plugins. An example added to the sample app could also be helpful to make sure not to interfere with the other plugins.

I will update the main README stating that there is a Dagger Plugin incubating via pull request.

I am at your service for any questions and will try to answer as fast as possible.

**Comment by holgerstolzenberg** [comment]
Merged and released. Thanks for your work!
