### ISSUE TITLE
To include multiple wsdl files in schema

### ISSUE THREAD

**Issue by sathish1295** [ewerk/gradle-plugins#130]
Hi all, 

I need to generate the classes with multiple wsdl files.

```
jaxb2 {

	xjc {
    'request-classes' {
      basePackage = *Package_name*
      schema = 'src/main/resources/wsdl/****.wsdl'
      additionalArgs = '-wsdl'
  	} }

  xjc {
    'addnl-classes' {
      basePackage = 'com.ford.vmacs.stub'
      schema = 'src/main/resources/wsdl/****.xsd'
  	}
  }
}
```

This doesn't works for me. Kindly anyone guide with this

**Comment by holgerstolzenberg** [comment]
Please be more specific on the error. "Doesn´t work for me" is not a suitable description for the error. Describe your Java version, env, Gradle version, what you did etc.

In the `xjc` configuration, is `*Package_name*` only a placeholder?

**Comment by sathish1295** [comment]
@holgerstolzenberg  Sorry for my mistake and wasting your precious time.   

I used Java 1.8 with gradle 5.6.

And sorry, after giving different package names  for both xjc, i solved it . 
Hence I am closing this issue, and Thank you for replying this issue.

Thanks

**Comment by sathish1295** [comment]
@holgerstolzenberg Sorry for wasting your time, This is my mistake and I have solved it.
