### ISSUE TITLE
Change compile to implementation

### ISSUE THREAD

**Issue by wwadge** [ewerk/gradle-plugins#131]
https://github.com/ewerk/gradle-plugins/blob/master/querydsl-plugin/src/main/groovy/com/ewerk/gradle/plugins/QuerydslPlugin.groovy#L97

Can you change the compile dependency to "implementation" (or make the adding a dependency optional) to make it compatible with Gradle 6+ ?

**Comment by holgerstolzenberg** [comment]
The 'new' querydsl plugin has a own repo:

https://github.com/ewerk/querydsl-plugin
