### ISSUE TITLE
Upgrade annotation-processor plugin to Gradle 6+

### ISSUE THREAD

**Issue by shafinmahmud** [ewerk/gradle-plugins#132]

**Comment by timpamungkas** [comment]
I'm using gradle 6, trying with querydsl 4.2.2. I see a lot of compile error when running `gradle build`, such as 

```
error: package org.springframework.web.bind.annotation does not exist
import org.springframework.web.bind.annotation.GetMapping;
```

So currently it is not possible to use gradle plugin with gradle 6?

I'm trying to use gradle 5 but the error persists.

**Comment by shafinmahmud** [comment]
I dont know why gradle plugin compatibility is so far behind. Gradle is the modern day build tool and it should get priority.

**Comment by holgerstolzenberg** [comment]
@shafinmahmud This is a non commercial open source project that is developed mostly in spare time. Feel free to contribute and make it available for Gradle 5+ anytime you need.

**Comment by holgerstolzenberg** [comment]
@timpamungkas The plugins not compatible with Gradle 5 ongoing. In terms of annotation processing, a lot of things changed with Gradle 5, what essentially makes the plugin obsolete. As of Gradle 5 annotation processing is supported out of the box by the `compileJava` tasks. I have not decided fully, but I think this might be a reason to discontinue the plugin, as I have no time at the moment…
