### ISSUE TITLE
Update querydsl-plugin to use querydsl 4

### ISSUE THREAD

**Issue by holgerstolzenberg** [ewerk/gradle-plugins#16]
Update the querydsl plugin to use querydsl 4 for annotation processing.

**Comment by holgerstolzenberg** [comment]
I just updated the plugin locally and tried to verify it with the sample application. Querydsl processing works so far but upgrading to querydsl 4 breaks compatibility of the Mongo annotation processing as `org.springframework.data.mongodb.repository.support.MongoAnnotationProcessor` comes from spring-data project that still uses querydsl 3.6.x with release version `org.springframework.data:spring-data-mongodb:1.7.0.RELEASE`.

@metawave @griffio Any thoughts on that?

**Comment by griffio** [comment]
Yes, my earlier response, l looked over in SpringData, https://jira.spring.io/browse/DATACMNS-670, they are discussing whether to force clients to move to querydsl 4.0.x. 
This querydsl plugin depends on the currently released version of Spring Data due to querydsl package renaming.

* We would have to wait for SpringData to move forward before implementing #16.
* I can provide #15 in a day or so and verify that querydsl 4.0.x processors can be configured as per the request.

**Comment by holgerstolzenberg** [comment]
That sounds reasonable. We will delay this one until https://jira.spring.io/browse/DATACMNS-670 is released.

**Comment by metawave** [comment]
Okay, sounds good to me. Just found a workaround to generate my morphia classes without any plugin defining a dependency to:

```
compile group: 'com.querydsl', name: 'querydsl-apt', version: '4.0.1', classifier: 'morphia'
```

which brings gradle to run the morphia annotation processor before the compileJava task. Cannot set the output folder (defaults to target/generated-sources/annotations) but that isn't a problem

**Comment by thekalinga** [comment]
Will this be addressed if we allow the user to customize even the annotation processor from the plugin configuration?

**Comment by griffio** [comment]
@thekalinga 
Hi,
Currently, it is addressed by using https://github.com/ewerk/gradle-plugins/tree/master/annotation-processor-plugin. You can get the same convenience using a generic annotation processor. This assumes you are using a single processor which is customised as required.

~~~groovy
plugins {
  id "com.ewerk.gradle.plugins.annotation-processor" version "1.0.0"
}

annotationProcessor {
  library "com.querydsl:querydsl-apt:4.0.0"
  processor "com.querydsl.apt.morphia.MorphiaAnnotationProcessor"
  sourcesDir "src/morphia/java"
}
~~~

**Comment by thekalinga** [comment]
Thanks for your response.

I realized the issue with my Spring data app after migrating to the newer version :). Will hold my apps' migration till querydsl is natively supported.

**Comment by holgerstolzenberg** [comment]
Seems like Spring-Data project has delayed this to its release milestone `Hopper`.

**Comment by griffio** [comment]
Hopper was released last week - https://spring.io/blog/2016/04/07/spring-data-release-train-hopper-goes-ga-and-sr1. This issue can be finally closed off.

I created a [project]( https://github.com/griffio/spring_data_hopper_ewerk_querydsl_plugin) for testing a snapshot version of the plugin 1.0.6-SNAPSHOT locally.

I can certainly provide the pull-request to close this issue if you want to proceed with moving to QueryDsl 4.0?

**Comment by thekalinga** [comment]
Are there any additional changes in your local 1.0.6-SNAPSHOT that's different from the published 1.0.5?

**Comment by griffio** [comment]
@thekalinga - no additional feature changes compared to current version 1.0.5.

For all users, the biggest breaking change is any of your projects using querydsl 3.x would have to upgrade to querydsl 4.x. Same if you are upgrading to Spring Hopper.

Maybe, the plugin should use semantic versioning, increment version up to 2.0, as **could** potentially break existing querydsl projects.

**Comment by holgerstolzenberg** [comment]
I´ll review the PR now...

**Comment by holgerstolzenberg** [comment]
Done.

@griffio Thanks for the PR.
