### ISSUE TITLE
Implement custom processor plugin

### ISSUE THREAD

**Issue by holgerstolzenberg** [ewerk/gradle-plugins#17]
@griffio Any further thoughts on this one before you start? Plugin naming for example.

**Comment by griffio** [comment]
I was thinking about "apt-plugin" or "processor-plugin" since the user is overriding the "-processor" switch. 

"There are only two hard things in Computer Science: cache invalidation and naming things."

**Comment by holgerstolzenberg** [comment]
I think 'processor-plugin' is a bit misleading. I think going a bit verbose with 'annoation-processor-plugin' is fine. Do you agree?

**Comment by griffio** [comment]
Agreed, the most descriptive name is 'annotation-processor-plugin'.

**Comment by holgerstolzenberg** [comment]
Okay so then I will await your PR.

**Comment by holgerstolzenberg** [comment]
Back from holidays, i will release the plugin by today.

**Comment by holgerstolzenberg** [comment]
PR was merged.
