### ISSUE TITLE
Error: Unable to load class 'org.gradle.platform.base.internal.toolchain.ToolResolver'

### ISSUE THREAD

**Issue by L3K0V** [ewerk/gradle-plugins#22]
I create new simple project with build.gradle:

```
plugins {
    id "java"
    id "com.ewerk.gradle.plugins.dagger" version "1.0.1"
}

 repositories {
    mavenCentral()
}

 dagger {
    library = "com.google.dagger:dagger:2.0"
}
```
and when I try to refresh (sync) gradle this error is returned:

> Error:Unable to load class 'org.gradle.platform.base.internal.toolchain.ToolResolver'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

Did I do something wrong?

PS. I'm using Gradle 2.6

**Comment by holgerstolzenberg** [comment]
Could you please try with Gradle 2.5?

**Comment by holgerstolzenberg** [comment]
I just tried by myself and it is definitely related to Gradle 2.6. Something of the internal API changed and broke backward compatibility. I will have to investigate it further. For the meantime, downgrade to Gradle 2.5 and everything is fine.

**Comment by L3K0V** [comment]
Okay, I will try and confirm with Gradle 2.5

**Comment by holgerstolzenberg** [comment]
I have just released all plugins and they are now compatible to Gradle 2.6
