### ISSUE TITLE
Cannot specify project module as library dependency for annotation processing

### ISSUE THREAD

**Issue by L3K0V** [ewerk/gradle-plugins#23]
Gradle build:
```
plugins {
    id "com.ewerk.gradle.plugins.annotation-processor" version "1.0.1"
}

annotationProcessor {
    library project(':compiler')
    processor 'com.full.path.to.processor'
    sourcesDir "src/main/java"
}
...
```

and when try to build:

``` 
Error:(6, 0) Gradle DSL method not found: 'library()'
Possible causes: The project 'SimpleProject' may be using a version of Gradle that does not contain the method.
...
```

Is there way to use annotation processor with project module dependency?

**Comment by holgerstolzenberg** [comment]
No, actually not. It doesn´t even make sense to me. The library is just a String holding the maven coordinates for the library to use for annotation processing.

**Comment by L3K0V** [comment]
For example I wrote my custom annotation processor for project and want to use it locally without push it to maven.

My project structure is as follow:

```
Project                                                
   +                                                   
   |                                                   
   +---+ Library project (with annotations)            
   |                                                   
   +---+ Compiler project using library                
   |                                                   
   +---+ Project specifying compiler for apt processing
```

In last project I try to use your plugin and process it with compiler project.

**Comment by L3K0V** [comment]
Is there any progress on this. I can try upcoming days or next week to implement it

**Comment by holgerstolzenberg** [comment]
This is a valid use case though. I will try to have a look at it next week.

@griffio If you think this can be done easily, could you provide a PR?

**Comment by griffio** [comment]
@L3K0V, firstly do you need help getting a gradle script to work with your project structure and annotation processor?  I can provide some examples so you can get working.

Secondly, we can look at changing the plugin and getting it published which will take into next week.

In the plugin, the library extension property would have to be changed to accept 'project' references. 
A reference to the "project(':compiler')" would be used and added to the configuration dependencies.
see plugin code http://git.io/vGdyC

e.g 
dependencies {
  annotationProcessor project(':compiler')
}

**Comment by L3K0V** [comment]
It would be great as soon as possible to provide mechanism to allow project references as dependencies, because there isn't available working and customizable annotation processing plugin for gradle which works with pure java (without android plugin) projects. 

Next week at some point I can try to implement it. I'm new in Gradle world and it will be interesting to me.

Greetings

**Comment by griffio** [comment]
Hi @L3K0V,

I have made a small change on a fork in issue#23 branch (github.com:griffio/gradle-plugins.git) 

Something for you to try and get something to work with.

Steps:

Ensure your Java 7 is java_home. Assumes up to date version of git.
~~~
git clone -b issue#23 --single-branch git@github.com:griffio/gradle-plugins.git issue23

cd issue23
~~~

( install the plugin to your local maven repo)

~~~
./gradlew :annotation-processor-plugin:install
~~~

(clone example of three module gradle project.)

~~~
git clone -b issue#23 git@github.com:griffio/gradle-project-apt-example.git issue23-example

cd issue23-example

./gradlew build
~~~

folder application/src/annotationProcessor should contain the generated files.

The plugin is using a module dependency to run the specified annotation processor.

Please feedback if this is the kind of project you are trying to build from.

Thanks, griffio.

**Comment by L3K0V** [comment]
Hi @griffio later today (in a few hours) will provide you feedback :)

**Comment by L3K0V** [comment]
@griffio It's working with 1.0.2 from issue#23 branch.

I compile annotation plugin from issue#23 and install it to local maven. Then some gradle.build changes and voalla. :)

Will you push this feature with a new version of the plugin?

Thanks, 
Asen

**Comment by griffio** [comment]
@L3K0V. Great that it helped you.

I will certainly create the PR for this shortly.

griffio.

**Comment by holgerstolzenberg** [comment]
I have release version 1.0.2 by now. It should ne available at the plugin portal.

@griffio Thanks for the fast PR.

**Comment by L3K0V** [comment]
Thanks to you all!
