### ISSUE TITLE
autovalue.shaded gets added to the compile classpath

### ISSUE THREAD

**Issue by nedtwigg** [ewerk/gradle-plugins#29]
I use Guava in my project - lots of `Preconditions` and `ImmutableList`.  I also use "auto-fix imports" a lot.  Now I've got a bunch of this in my project:

```java
import autovalue.shaded.com.google.common.common.base.Preconditions;
import autovalue.shaded.com.google.common.common.collect.ImmutableList;
```

when what I really want is the regular guava classes without the `autovalue.shaded` stuff.  Worse still, the project compiles great!

Maybe there's no way to put `@AutoValue` on the classpath without putting this stuff in there too.  But since the `@AutoValue` annotation is only used during code generation, it would be nice if these `autovalue.shaded` mistakes were compile errors.

**Comment by griffio** [comment]
@nedtwigg 

Hey, I have come across this before, seen it in other projects that use autovalue.

I got around it by configuring the editor(Intellij), sure ecplise has something too, that will ignore the shaded package names.

In this case they (autovalue) shade guava and apache.commons.
This is likely to isolate themselves from main guava releases which has a "huge" surface area for breaking changes! Various open source projects are avoiding shipping guava dependencies for this reason.

Sorry, don't know any other solution that we can provide.

If I think of something I will post back.

Regards griffio.
