### ISSUE TITLE
Generated sources are not being added to javac sources by the plugin

### ISSUE THREAD

**Issue by griffio** [ewerk/gradle-plugins#3]
In the querydsl plugin, when there are references of "Q" classes from Java code in "src/main/java" the compileJava task fails. 

e.g
```java
package com.ewerk.gradle.plugins.sample;

public class AnyPredicates {

    static QAnyJpaEntity anyJpaEntity = QAnyJpaEntity.anyJpaEntity;

}
```
Running the ./gradlew compileJava --debug shows that the generated sources are not being added to javac.

Previously, when setting up the annotation processor manually in gradle I would add generated sources concatenated to the compileJava task source property. 

e.g.
```groovy
compileJava {
     source = sourceSets.main.java + sourceSets.generated.java
}
```

This doesn't appear to work in the querydsl plugin, even though the plugin is adding a "registerSourceAtCompileJava".

I will have a look at seeing if the compileJava task is being configured with the supplied values or not being invoked in the plugin.

**Comment by holgerstolzenberg** [comment]
Strange thing. Just for clarification:

"In the querydsl plugin, when there are references of "Q" classes from Java code in "src/main/java" the compileJava task fails."

Wouldn´t that mean that the plugin cannot work at all, because Q classes will never be found within `src/main/java`?

I added the line `static QAnyJpaEntity anyJpaEntity = QAnyJpaEntity.anyJpaEntity;` from the code snippet you provided to class `Sample` (within sample-application) and it compiled without problems.

**Comment by holgerstolzenberg** [comment]
Further investigations from you are very welcome.

**Comment by griffio** [comment]
Ok - will try and come up with something that works for me tomorrow.

How do you see usage of querydsl in a application e.g with Springdata?

IntelliJ will compile ok as the sources are configured but it is the gradle build that fails.

I would expect it to work at least the same as Autovalue, the com.ewerk.gradle.plugins.sample.Bean is referencing the generated AutoValue_Bean.

There are some differences between processors and perhaps fall into two usage patterns.

For example:

* Autovalue generates java classes that are not accessed outside the abstract class 
and the processor uses Services Provider extension for discovery, performs compilation.

* QueryDsl generates API java classes and uses explicit processor discovery, processor only.

**Comment by griffio** [comment]
After trying it on a [test  branch](https://github.com/griffio/gradle-plugins/tree/querydsl-issue/querydsl-plugin), I think having a single Querydsl annotation processor is the way to go,
as it fixed the problem I was experiencing, and removes a bunch of classes from the plugin.

e.g Single task required for annotation processing
```groovy
class QuerydslAnnotationProcessor extends JavaCompile {

    QuerydslAnnotationProcessor() {

        setSource(project.sourceSets.main.java)

        setClasspath(project.configurations.compile)

        def processors =  project.querydsl.activeProcessorClassNames.join(",")

        options.compilerArgs = [
                "-verbose",
                '-proc:only',
                "-processor", processors
        ]

        destinationDir = project.file(project.querydsl.querydslSourcesDir)
    }

}
```

**Comment by holgerstolzenberg** [comment]
A pull request is very welcome as I am short on time. I´d prefer naming the task `QuerydslCompile` as naming it `QuerydslAnnotationProcessor` is a bit confusing.

**Comment by holgerstolzenberg** [comment]
Merged the PR. Will test it now and release it today if no problems occur.

**Comment by griffio** [comment]
Ok - great.
In the sample-application/build.gradle you can also set querydslDefault = true since I added
the AnyQueryEntity class to generate a model if enabled.

e.g
```groovy
querydsl {
 ...
  querydslDefault = true
}
```groovy

**Comment by holgerstolzenberg** [comment]
Done. Plugin is released and available through portal. Docs are updated. Good job @griffio.
