### ISSUE TITLE
Add Jaxb2 Plugin for generating Java sources from XSD

### ISSUE THREAD

**Issue by holgerstolzenberg** [ewerk/gradle-plugins#30]

**Comment by holgerstolzenberg** [comment]
@griffio 

I just pushed the new JAXB2 plugin to the repo. I´d like you to do a review and share your thoughts.

The point I am currently thinking about the most is the configuration of dependencies. It was a real pain to figure out which dependencies to use. I am not sure if it is really necessary to give the end-user the opportunity to configure the dependencies of the `jaxb2` configuration by themselves. What do you think? Just add the dependencies to the plugin directly.

**Comment by griffio** [comment]
@holgerstolzenberg 
Sure will check it out.
My initial thought is that as this wraps an existing ant task (JAXB2) then it should follow same configuration options for dependencies. 
However, I think the current dependencies you have can be upgraded from "com.sun"? 
https://stackoverflow.com/questions/26413431/which-artifacts-should-i-use-for-jaxb-ri-in-my-maven-project
Regards.
@griffio

**Comment by griffio** [comment]
@holgerstolzenberg 
The only other suggestion to make, after creating a test project, is to make the default 'generated' directory the same name as the configuration name "jaxb2".

https://github.com/ewerk/gradle-plugins/blob/master/plugins/jaxb2-plugin/src/main/groovy/com/ewerk/gradle/plugins/tasks/XjcTaskConfig.groovy#L13

Intellij, for some reason, creates the a configuration from this name.
https://github.com/ewerk/gradle-plugins/blob/master/plugins/jaxb2-plugin/src/main/groovy/com/ewerk/gradle/plugins/Jaxb2Plugin.groovy#L52

Not urgent - but it removes an extra folder from Intellij.

Regards, griffio.

**Comment by holgerstolzenberg** [comment]
https://plugins.gradle.org/plugin/com.ewerk.gradle.plugins.jaxb2
