### ISSUE TITLE
Drop JDK-7 support

### ISSUE THREAD

**Issue by holgerstolzenberg** [ewerk/gradle-plugins#31]
@griffio what do you think about that?

**Comment by griffio** [comment]
@holgerstolzenberg 

No problem for me - I don't have any requirements for 1.7.

What breaks currently if this is made the default for plugin development?

Travis CI should be able to run JDK 8 to make builds, initially compiled with target 1.7.

Development environment, should work if the user chooses to run with jdk8. (Most IDEs are now 1.8)

Is there anything that requires JDK 8 language/library features?  Plugins are written in groovy.

Are there language features, lambda, streams etc used in any dependencies that the user provides?
 
Android Studio development should work the same as Intellij

Regards,

@griffio

**Comment by holgerstolzenberg** [comment]
Upgrading will mean that end users have to use JDK-8 for all plugins we will release in the future. Thats the only thing I am thinking about. Your list of points is good, they are all safe for me too.

**Comment by holgerstolzenberg** [comment]
jaxb2-plugin released with JDK-8 required

**Comment by ieugen** [comment]
Please don't do that. You will force all users of your plugin to require jdk-8 which is not a good idea. 
Do you really need the jdk-8 features? 
IDE's do not require jdk-8 as of yet. Intellij plans this for version 16. I'm sure it will be the same for Eclipse/Netbeans [1] 

Current Debian stable does not ship with JDK-8 by default. It is still 7. The next version will be 8, next year by this time [2]. 

[1] https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under
[2] https://packages.debian.org/jessie/java/default-jdk

**Comment by holgerstolzenberg** [comment]
Well its a hard consideration here. I my opinion, if the community would push faster/harder, JDK-7 won´t be a topic here.

The thing is, all plugin versions released until now will still be usable with JDK-7. Only new releases after JDK-8 compliance won´t be available to JDK-7 users.

Currently there are no plans for feature upgrades of the plugins as they work for us like they are right now. (Except reported bugs)

I can understand our thoughts though I like to stay in touch to current version especially thinking about having JDK-9 around the corner.

@griffio What do you think?

**Comment by griffio** [comment]
A year ago I would have said stick with JDK 7, I am inclined to agree that JDK 8 as default for the development environment is now the reality. Currently the plugin builds have that set.
Unless you want to publish one last 1.7 targeted build for all plugins and document that as the final supported version?

**Comment by holgerstolzenberg** [comment]
I agree. I will update the plugins to JDK-8 by the end of the week I think.

**Comment by holgerstolzenberg** [comment]
The `querydsl-plugin` default JDK is now 1.8

**Comment by holgerstolzenberg** [comment]
The `annotation-processor-plugin` default JDK is now 1.8.

**Comment by holgerstolzenberg** [comment]
The `auto-value-plugin` default JDK is now 1.8.

**Comment by holgerstolzenberg** [comment]
The `auto-value-plugin` default JDK is now 1.8

**Comment by holgerstolzenberg** [comment]
The `integration-test-plugin` default JDK is now 1.8

**Comment by holgerstolzenberg** [comment]
The `jaxb-test-plugin` default JDK is now 1.8

**Comment by holgerstolzenberg** [comment]
The `querydsl-plugin` default JDK is now 1.8

**Comment by holgerstolzenberg** [comment]
Updated sample application.

**Comment by ben-manes** [comment]
The changelog for the autoValue plugin claims 1.0.8 has been released, but the [plugin portal](https://plugins.gradle.org/plugin/com.ewerk.gradle.plugins.auto-value) only has 1.0.7. Not a big deal, but seems that you forgot to release that version.

**Comment by holgerstolzenberg** [comment]
I really forgot that. Fixed as of f68d1c3aaec4884af0665cb38b918cb286482415.
