### ISSUE TITLE
dagger-plugin should fail to clean files not @Generated

### ISSUE THREAD

**Issue by karlthepagan** [ewerk/gradle-plugins#32]
steps:
1. configure build using dagger { daggerSourcesDir = 'src/main/java' }
2. gradle clean assemble
3. all source files were deleted. panic, then recover files using git / local file history

alternative resolution: dagger-plugin should fail its clean task if daggerSourcesDir is equal to another entry in the sourceSets

**Comment by griffio** [comment]
Hi @karlthepagan,

Yep, this is a 'foot-gun' that can happen to a user.

We can apply the fix to the autovalue plugin from [issue27] (https://github.com/ewerk/gradle-plugins/issues/27), I will update the same fix for this plugin, Dagger, too.

Generally, when source/generated source are co-located annotation processors get confused anyway. However, we shouldn't delete your code though!

Thanks. @griffio.

**Comment by karlthepagan** [comment]
Thanks! I was hoping to shortcut problems I was having with a plugin that doesn't respect the sourceSets conventions, but I'll get off my butt and fix that plugin now! ;)

**Comment by griffio** [comment]
@karlthepagan,
Ok cool, I will issue a fix for the 'foot-gun' problem anyway, and will then close the issue.
This plugin expects that source and generated are separate sourceSets and should work as default out of the box.

Typically annotation processors, like Autovalue and Dagger2 will put their generated files under project/build tree but we want it to work easily with Intellij.

Regards, @griffio.

**Comment by holgerstolzenberg** [comment]
Done with 2e9f166d6bed9db8ea75b00094c86de5f0093b5b
