### ISSUE TITLE
How do I use this plugin to generate QueryDSL classes from a SQL DB?

### ISSUE THREAD

**Issue by gilbertg** [ewerk/gradle-plugins#34]
Hi, How do I use this plugin to generate QueryDSL classes from a SQL DB?
This link: https://gist.github.com/jbrackett/095801f357f7e7673dc6
is an example of what we are trying to do - can this plugin do that in a neater way?
~gilbert

**Comment by holgerstolzenberg** [comment]
The plugin is not intended to do that for you, it follows another use case by creating the `Q` classes from a JPA model. Currently we have no plans implementing a plugin for creating `Q` classes from the SQL model (reverse engineer), as this use case is very rare to us.

This may change in the future.

We would be happy though if you like to provide the plugin as a PR.
