### ISSUE TITLE
Annotation Processor Catch 22

### ISSUE THREAD

**Issue by ethauvin** [ewerk/gradle-plugins#35]
It must be something very obvious, but I simply can't figure it out.

Using the Annontation Processor `:compileAnnoationProcessor` execute my processor as expected, but `:compileJava` fails because my processor's annotation classes cannot be found. If I include my processor to the `dependencies`, then `:compileJava` will fail attempting to again generate the code wich results in duplicate classes.

Any help would be greatly appreciated.

Here's a [very simple example](https://github.com/ethauvin/AnnotationProcessorTest) that illustrates the problem.

**Comment by griffio** [comment]
Hi @ethauvin,
I will try it out and get back to you soon.
Could be that you don't need a plugin if the annotation processor is being picked up in the class-path and executed by the compiler automatically.
Regards, @griffio

**Comment by ethauvin** [comment]
Thanks, @griffio. That's entirely possible, but I was really looking forward to be able to use the plugin's sourcesDir location for generated source.

**Comment by griffio** [comment]
Hi @ethauvin,

I have created a fork that seems to work ok. (Also There was a typo in your package name).

https://github.com/griffio/AnnotationProcessorTest/blob/master/build.gradle

Usually, to test something I create a gradle build manually that does there same as the plugin. It's not magic.

Intellij friendly.

run ./gradlew clean run.

I will now test with the plugin configuration.

**Comment by griffio** [comment]
@ethauvin 
Ok, slight tweak needed in your build script for plugin use with this processor to avoid running the processor twice.
Because the annotation processor needs to be in the main classpath - it will be discovered automatically.
So, we just switch annotation processor off in build javac by adding  '-proc:none',
The plugin has its own task and run the proc.

Here below is a plugin build script.

```
plugins {
  id "com.ewerk.gradle.plugins.annotation-processor" version "1.0.2"
}

apply plugin: 'java'
apply plugin: 'application'

repositories {
  maven {
    url "http://dl.bintray.com/cbeust/maven"
  }
}

project.ext.sourceCompatibility = JavaVersion.VERSION_1_8
project.ext.targetCompatibility = JavaVersion.VERSION_1_8
version = '0.1'

defaultTasks 'run'

mainClassName = 'net.thauvin.erik.annotproctest.Example'

compileJava {
  options.compilerArgs += [
      '-proc:none',
  ]
}

dependencies {
  compile(
      "com.beust:version-processor:0.2"
  )
}

annotationProcessor {
  library "com.beust:version-processor:0.2"
  processor "com.beust.version.VersionProcessor"
  sourcesDir "src/annotationProcessor/java"
}
```

Hope that helps regards @griffio

**Comment by ethauvin** [comment]
Thanks, @griffio. Worked like a charm.

Might I suggest that something be added to the plugin's documentation regarding;

```groovy
compileJava {
  options.compilerArgs << '-proc:none'
}
```

It might save people quite a bit of time...

Thanks again! :+1:
