### ISSUE TITLE
[jaxb2-plugin] Support incremental builds

### ISSUE THREAD

**Issue by steinsag** [ewerk/gradle-plugins#38]
Currently, whenever I run `gradle build`, jaxb2-plugin will generate all classes. This should only happen when my schemas changed or when something changed in the destination directory.

In Gradle, this is called incremental build. See e.g. http://gradle.org/feature-spotlight-incremental-builds/

I believe incremental build support can be easily added in https://github.com/ewerk/gradle-plugins/blob/master/plugins/jaxb2-plugin/src/main/groovy/com/ewerk/gradle/plugins/tasks/GenerateJaxb2Classes.groovy, but I don't know how to compile and test a new plugin version.

**Comment by holgerstolzenberg** [comment]
The easiest way would be to apply your changes, then build the plugin SNAPSHOT and install it to your local maven repo.

```bash
[…]/gradle-plugins/plugins/jaxb2-plugin> ../../gradlew build install
```

Then you can modify the sample apps `build.gradle`, uncomment the line where the released version is applied from the Gradle plugin portal, add a `buildScript` section that uses `mavenLocal` as repository and apply the SNAPSHOT plugin via `apply plugin: ...`

**Comment by steinsag** [comment]
Can't get dev setup to work. Here my branch:

https://github.com/steinsag/gradle-plugins/tree/feature/incremental-builds

I installed the changed plugin locally (gradle build install) and verified that it is present in my local maven directory:

    ls ~/.m2/repository/com/ewerk/gradle/plugins/jaxb2-plugin/1.0.2-SNAPSHOT
    jaxb2-plugin-1.0.2-SNAPSHOT-groovydoc.jar  jaxb2-plugin-1.0.2-SNAPSHOT.jar  jaxb2-plugin-1.0.2-SNAPSHOT-javadoc.jar  jaxb2-plugin-1.0.2-SNAPSHOT.pom  jaxb2-plugin-1.0.2-SNAPSHOT-sources.jar  maven-metadata-local.xml

But when compiling the sample app, I get that he can't find the snapshot dependency.

**Comment by holgerstolzenberg** [comment]
Well the error shows that you forgot to add the **local** maven repo to the `buildScript` repos. Please stick to my previous comment for details.

**Comment by steinsag** [comment]
Actually no, see: https://github.com/steinsag/gradle-plugins/blob/feature/incremental-builds/sample-application/build.gradle#L3

**Comment by holgerstolzenberg** [comment]
You need to apply the plugins you want out of the local repo with `apply plugin: …` and their SNAPSHOT version. Also need to remove them from the `plugins {}` section as this plugins are always loaded from the portal with there release version.

**Comment by steinsag** [comment]
Ok, I give up. I was able to run my locally compiled plugin, but can't get incremental build to work.

Please take a look at it as supporting incremental builds is one of the main core features of Gradle. Without this kind of support, **this plugin is pretty useless** as it will regenerate sources with each gradle run! This is a big waste of time. In my case, generating the sources and compiling them takes 20 seconds, but the schema rarely changes. So I loose 20 seconds on each gradle run!

I provided links about incremental build feature in my initial post, but here a few more:

https://docs.gradle.org/current/userguide/more_about_tasks.html (section 17.9)
https://docs.gradle.org/current/userguide/custom_tasks.html (section 38.4)
https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskInputs.html
https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskOutputs.html

Afaik, the task InitJaxb2SourcesDir is the first one to change as it should only create the source dirs (i.e. output dirs) if they are not present yet.

**Comment by holgerstolzenberg** [comment]
Your suggestion is definetly an enhancement for the plugin to be implemented.

Still, claiming the plugin is pretty useless is a tough one, especially not providing a solution. For us it worked pretty well so far because we did not have very large schemas to process right now.

I will try to improve the plugin within this week.

**Comment by griffio** [comment]
I had a look at this and we can lean on the existing update-to-date checking in xjc already - xjchttps://jaxb.java.net/2.2.4/docs/xjcTask.html.

So, a solution doesn't specifically require gradle's incremental input/output setup to be implemented.

You will see there is a recompilation check using produces/depends fileset based on the timestamp of the scheme file.

I have created a PR that implements the feature on the xjc task in the plugin.

Example project using the snapshot change - https://github.com/griffio/jaxb2-ewerk-incremental-sample

As below, it is important to note that the **produces** fileset should contain files for each schema config, e.g, src/generated/foo, by transforming the generated directory with the package name; as it is possible for multiple schemas to be output under the same generated source root. 
~~~
ant.xjc(destdir: generatedSourcesDirParent,
              package: theConfig.basePackage,
              schema: schemaFile) {
        depends(file: schemaFile)
        produces(dir: generatedSourcesDirPackage, includes: "**/*.java")
~~~

**Comment by holgerstolzenberg** [comment]
I have just released version `1.0.2` of the plugin.
https://plugins.gradle.org/plugin/com.ewerk.gradle.plugins.jaxb2

@steinsag Can you give it a try?

**Comment by griffio** [comment]
@holgerstolzenberg can we close this now?
If so, I can provide the PR to fix it up as the change-log and read-me need to be updated with current released versions.

**Comment by steinsag** [comment]
Sorry for not responding earlier. I can't give it a test right now. I won't have access to my test environment the next 10 days, but will check it for sure!
