### ISSUE TITLE
Module groups cyclic dependencies with QueryDSL plugin and IntelliJ IDEA 2016

### ISSUE THREAD

**Issue by vlastikcz** [ewerk/gradle-plugins#49]
Steps:
 1. Create project with a module like this:
   - modules/car/build.gradle
   - modules/car/src/main/java (entitites and services here)
   - modules/car/src/querydsl/java (generated classes here)
   - modules/car/src/test/java (tests here)
 2. Build the project and open it in IntelliJ IDEA 2016

Expected:
In IntelliJ IDEA 15 and older, there was a single module called `car` and it was possible to reference between classes in the `main/`, `querydsl/` and `test/` source roots.

Actual:
In IntelliJ IDEA 2016, the `build.gradle` actually does not represent a module, but rather a module group called `car` with modules `car_main`, `car_querydsl` and `car_test` (based on the `car` subdirectories). 

And dependencies between this 3 modules has to be explicitly defined (e.g. `car_test` depends on `car_main`). But with QueryDSL, there is an issue, as the `car_querydsl` has to depend on the `car_main`. But usually, the services/DAOs from `car_main` will also depend on the `car_querydsl`, which will create a circular dependency.

I did some research and I think that possible solution would be to generate the querydsl classes into the `car_main` module, but I would like at least to change the package of generated classes (so they wont be in the same dir as entities). I found the `querydsl.packageSuffix` APT property (http://www.querydsl.com/static/querydsl/3.2.0/reference/html/ch03s03.html), but I couldn't  find a way how to set it from Gradle.

*com.ewerk.gradle.plugins.querydsl* version: 1.0.5

**Comment by griffio** [comment]
Try this,
project.tasks.compileQuerydsl.options.compilerArgs << '-Aquerydsl.packageSuffix=Foo'

**Comment by vlastikcz** [comment]
Thank you, it really worked. Maybe it could be added to the `readme.md`.

But as I found, the Spring Data requires the QueryDSL to be in the same packages as entities (no in the default anyway, because of the `SimpleEntitypathResolver.java`). So the suggested solution cannot be used.

And as I found today, the fix will be probably included in new IntelilJ release (https://youtrack.jetbrains.com/issue/IDEA-152581), so it does not make much sense to modify the build/plugin because of that.

Thank you for you help!

**Comment by griffio** [comment]
Hi,

If you want to keep the Intellij 15 behaviour download the latest IDEA 2016 EAP Version.

There is now a new option under Gradle - builds - **create separate module per source set.**

**Uncheck** this option and it will flatten the modules into a single module.

Also, if it's possible that you can close the issue  - Thanks.

**Comment by vlastikcz** [comment]
I've downgraded to InteliiJ IDEA 15 for now. Thank you.
