### ISSUE TITLE
AutoValue Plugin : setting autoValueSourcesDir has no effect

### ISSUE THREAD

**Issue by martintreurnicht** [ewerk/gradle-plugins#5]
The issue that i'm having and i'm sure everyone is having is that it puts the generated sources in `build/classes/main/generated` or `build/classes/test/generated_tests`. I'd like to have it change it's root directory to `build/generated` where it then creates it's relative structures ex. `src/main/java` and `src/test/java`

**Comment by holgerstolzenberg** [comment]
Sorry. I cannot follow your argumentation. At first `autoValueSourcesDir` has a effect. It is the folder where your generated auto-value beans will be put. Changing `autoValueSourcesDir` to another folder puts the beans there, I just tested again with the sample application.

The auto-value beans are source files that are created during compilation. We are using a own Gradle `sourceset` for the auto-value classes. This normally results in a directory structure like this:

```
/- build
|    - classes
|         - main
|             - my-package
|         - test
|             - my-package
|- src
|    - main
|         - my-package
|    - auto-value
|         - my-package
|    - test
|         - my-package
|
| build.gradle
```

As the `sourceset` uses `build/classes/main` and `build/classes/test` out of the box, the structure assembled represents the final structure of the target jar.

Changing the default output folder of the `sourceset` to `build/generated` would mean that we would have to deal a lot with other configuration/classpath issues to get the final artefact packaged or published.

I do not think we are going to support this, but maybe you can give more details about your use case.

**Comment by martintreurnicht** [comment]
Ok so i've finally created a sample project. In this sample project things seem to work fine. But i still have the issue that if you create autoValue classes in any other sourceSet than main, it doesn't pick it up in your IDE. This isn't a major issue or probably an issue for most people but it does limit the way you can use it though. There should probably be a naming strategy like `auto-value-{sourceSet}` which means `auto-value-main`, `auto-value-test` etc

**Comment by holgerstolzenberg** [comment]
We are using IntelliJ Idea and the source set gets picked up. If your IDE does not, it is a problem with the IDE tooling not with the plugin itself. You may want to try out `eclipse` or `idea` plugin.

I do not get your idea with the naming strategies. There is no need to have a separate test directory for the `auto-value` sources. You just test these source like the main sources from within your `test` or `integration-test` source set.
