### ISSUE TITLE
querydslSourcesDir param does not work with passed value

### ISSUE THREAD

**Issue by renatoaraujoc** [ewerk/gradle-plugins#51]
Hello,

After much investigation, at class com.ewerk.gradle.plugins.tasks.QuerydslCompile, on line 28, the value of _project.file(project.querydsl.querydslSourcesDir)_ does not reflect the new value passed by: _querydsl { querydslSourcesDir = 'some/new/dir' }_

I've tried my best to fix the issue myself by cloning your project, but since I'm new with Gradle, I couldn't succeed. 

Looking forward for this fix,

Thank you!

**Comment by griffio** [comment]
@renatoaraujoc, 

Thanks for taking the time and trying to work it out yourself - I will have a look and see if the new value is being passed to the javac annotation processor. 

Are you using Android or Java project?

With gradle, this command would provide more logging details that can help.
~~~
./gradlew --info build  
~~~

**Comment by renatoaraujoc** [comment]
@griffio,

It works as expected, thank you!

I'll fork the main plugin file to propose an addition to those who use the IdeaPlugin to automatically add a:
`project.idea {
    module {
        generatedSourceDirs += file
    }
}`

You can close this issue :)

**Comment by griffio** [comment]
@renatoaraujoc,

Glad it works now - a new plugin version would be released with the fix.

As for IdeaPlugin, this is not used inside any of the ewerk plugins as Intellij's Gradle plugin, for example, should use the Gradle API to "mark" source, test folders from the build file.

The ```project.idea { module { generatedSourceDirs += file } }``` is only necessary when users start adding generated source under projectDir/build and Intellij can't flag it as source automatically. 

So we would unlikely take PRs adding "IdeaPlugin" references into any plugin files.

**Comment by holgerstolzenberg** [comment]
Querydsl plugin version `1.0.7` released by now.

https://plugins.gradle.org/plugin/com.ewerk.gradle.plugins.querydsl
