### ISSUE TITLE
QuerydslCompile task should take into consideration providedCompile and providedRuntime

### ISSUE THREAD

**Issue by ilx** [ewerk/gradle-plugins#6]
QuerydslCompile task should take into consideration providedCompile and providedRuntime added by the war plugin.
Also, it should be possible to extends classpath with arbitrary libs.

**Comment by holgerstolzenberg** [comment]
So in the end we have to issues here:

" it should be possible to extends classpath with arbitrary libs" -> #7

**Comment by holgerstolzenberg** [comment]
@ilx What do you want to achieve with this. Could you please add some detail on your use case.

**Comment by ilx** [comment]
Classes may contain annotations found in dependencies provided by runtime container 
(I use propdeps-plugin for such dependencies) and querydsl annotation processor will fail if it encounters unknown classes (currently the ones outside compile scope).

**Comment by holgerstolzenberg** [comment]
Yeah you are right. Sounds reasonable. I am currently under project load and will be for holidays afterwards. The soonest I will be able to provide that feature is mid of april.

**Comment by holgerstolzenberg** [comment]
Pull requests welcome though.

**Comment by holgerstolzenberg** [comment]
Fixed by ef2a3ab6cb85226d641b712568b5dca5aba0bdf3.
