### ISSUE TITLE
Querydsl plugin 1.0.8 is not available in gradle plugins

### ISSUE THREAD

**Issue by TheKojuEffect** [ewerk/gradle-plugins#60]
`1.0.7` is the latest version in gradle plugins site but `1.0.8` is listed in documentation page.

https://plugins.gradle.org/plugin/com.ewerk.gradle.plugins.querydsl

**Comment by holgerstolzenberg** [comment]
That is correct as the plugin version `1.0.8` has not been released so far. I have updated the invalid `changelog.md` and appendend the SNAPSHOT information.

**Comment by TheKojuEffect** [comment]
Hey @holgerstolzenberg, Thanks for the quick response :)

**Comment by rafik777** [comment]
@holgerstolzenberg When can we expect the publication of 1.0.8 version?
How can we use the current 1.0.8-SNAPSHOT in our build.gradle? 
Is there 1.0.8-SNAPSHOT in any public maven repository?

**Comment by holgerstolzenberg** [comment]
I´ve released and published the plugin by now. Please see `https://plugins.gradle.org/search?term=querydsl`.

@rafik777 The use the `SNAPSHOT` version, you will have to check out the sources and build the plugin on your own which should be really straightforward.

**Comment by rafik777** [comment]
@holgerstolzenberg After upgrade I have:
Cannot change dependencies of configuration ':compile' after it has been included in dependency resolution.

Used versions:
id "com.ewerk.gradle.plugins.querydsl" version "1.0.8"
compile "com.querydsl:querydsl-jpa:4.1.3"
gradle: 3.3
