### ISSUE TITLE
annotation processor compile with additional arguments

### ISSUE THREAD

**Issue by weisebrazil** [ewerk/gradle-plugins#62]
Some annotations processors have the @SupportOptions annotation. But the plugin haven't the configuration to do it. 

* -Akey[=value] : Used to pass options to the processors. Only those options registered with the SupportedOptions annotation are passed to a processor.

**Comment by holgerstolzenberg** [comment]
Merged your pull request and release plugin version 1.0.3 right now.

https://plugins.gradle.org/plugin/com.ewerk.gradle.plugins.annotation-processor

**Comment by holgerstolzenberg** [comment]
@weisebrazil Thanks for your contribution!
