### ISSUE TITLE
compileQuerydsl running every build, even when not needed

### ISSUE THREAD

**Issue by Ramblurr** [ewerk/gradle-plugins#68]
In my setup `compileQuerydsl` is being run on every `gradle build` or `gradle bootRun` (using spring boot in my case), even though there was no `clean` done and nothing has changed with the Q classes or the entities.

`compileQuerydsl` adds 33 seconds to my boot time, and I'd love to cut that down.

Is there a way to only have `compileQuerydsl` run 

1. only when the Q classes don't exist or
2. or when the Entities have changed?

**Comment by griffio** [comment]
hey @Ramblurr, what is the directory for the generated sources you are using in your build? I will see if I can replicate this behaviour - may take me a couple of days to get back to you though.

**Comment by Ramblurr** [comment]
Thanks @griffio !

This is my generated sources dir:

```
def generatedSourcesDir = "$buildDir/generated-sources/apt"
```


This is the entirety of my config related to query dsl:

```groovy
/*
    BEGIN: querydsl configuration
 */
def generatedSourcesDir = "$buildDir/generated-sources/apt"

querydsl {
    querydslSourcesDir = generatedSourcesDir
    hibernate = true
}

sourceSets {
    main {
        java {
            srcDir generatedSourcesDir
        }
    }
}

idea {
    module {
        generatedSourceDirs += file(generatedSourcesDir)
        downloadSources = true
    }
}

// custom task that generates the native sql classes by reading the schema from the db
// it piggybcks onto the compileQuerydsl task
task generateQueryDslClasses(group: 'querydslsql') {
    outputs.files generatedSourcesDir
    doLast {
        ant.taskdef(
                name: 'generateQueryDsl',
                classname: 'com.querydsl.sql.codegen.ant.AntMetaDataExporter',
                classpath: configurations.querydsl.asPath
        )
        ant.generateQueryDsl(
                jdbcDriver: 'org.postgresql.Driver',
                jdbcUrl: project.property('flyway.url'),
                jdbcUser: project.property('flyway.user'),
                jdbcPassword: project.property('flyway.password'),
                packageName: 'com.my.package.sql',
                namePrefix: 'SQ',
                targetFolder: generatedSourcesDir
        )
    }
}
compileQuerydsl.dependsOn generateQueryDslClasses

// This makes lombok and querydsl play nicely together
project.afterEvaluate {

    project.tasks.compileQuerydsl.options.compilerArgs = [
            "-proc:only",
            "-processor", project.querydsl.processors() +
                    ',lombok.launch.AnnotationProcessorHider$AnnotationProcessor'
    ]
}

/* END: querydsl configuration */
```

**Comment by griffio** [comment]
Hey @Ramblurr , is it possible that the Lombok processor is 'touching' source files and making the 'Q' files regenerate? I tried one of my Spring projects and 'build' will only compile if source has changed. You can run ./gradlew --debug build and see if gradle is detecting changes to files.

**Comment by holgerstolzenberg** [comment]
@Ramblurr Any news on this one? Otherwise I am going to close this issue soon as it seems to be a false positive.

**Comment by Ramblurr** [comment]
It is still double building, but I doubt it is a bug in this plugin. I need to investigate @griffio 's suggestion.
