### ISSUE TITLE
AutoValue autoValueTestSourcesDir support

### ISSUE THREAD

**Issue by ben-manes** [ewerk/gradle-plugins#69]
When using `@AutoValue` in a test class the generated `.java` code appears in `build/classes/test/`. This is not in the sourceSet of course, so the IDE doesn't include it.

Am I misunderstanding how to use this plugin to codegen for tests or is it not supported?

**Comment by holgerstolzenberg** [comment]
This is a use case we never looked at. I always used the `@AutoValue` classes within `main` production code. Am I understanding you right that you have inner classes in your tests that you annotate with `@AutoValue`. Can you please provide more info on how your project is set up.

**Comment by ben-manes** [comment]
Yes. I normally use it in my `main` classes, but today was writing a fake object for a unit test. I immediately reached for autovalue to create a builder and realized it wasn't available. It was trivial to write it by hand, but it would be nice to reduce test noise by having the tool available there too.

**Comment by holgerstolzenberg** [comment]
Well it should be no problem to configure Gradle or your IDE to pickup `build/classes/test` as a source set.

**Comment by ben-manes** [comment]
That's ugly since there's compiled classes there. I'd probably use a copy task to move the sources into a separate directory.

**Comment by holgerstolzenberg** [comment]
I´ll take a deeper look into that next week. Would be great if you document your findings here.

**Comment by ben-manes** [comment]
This was easier than I thought and mirrors the `compileJava` setup you use. It would be nice to generalize your usage to work against all sourceSets, which would make it work with new features such as the `java-library` api/impl separation or customizations.

Below is the script I've added to the project, `autoValue.gradle`. Note that I had to disable `compileAutoValueJava` recently which broke the build prior to this change, but I haven't dug into why it appeared.

```gradle
apply plugin: 'com.ewerk.gradle.plugins.auto-value'

def autoValueBaseDir = "${buildDir}/generated-sources/autoValue/"
def autoValueTestSourcesDir = "${autoValueBaseDir}/test"

sourceSets.test.java.srcDirs += autoValueTestSourcesDir

autoValue {
  library = libraries.auto_value
  autoValueSourcesDir = "${autoValueBaseDir}/main"
}

afterEvaluate {
  tasks.compileAutoValueJava.enabled = false
}

compileTestJava {
  options.compilerArgs = options.compilerArgs + ["-s", autoValueTestSourcesDir]
}

task cleanAutoValueTestSourcesDir {
  doFirst {
    file(autoValueTestSourcesDir).deleteDir()
  }
}
clean.dependsOn(cleanAutoValueTestSourcesDir)

task initAutoValueTestSourcesDir {
  doFirst {
    file(autoValueTestSourcesDir).mkdirs()
  }
}
compileTestJava.dependsOn(initAutoValueTestSourcesDir)
```
