### ISSUE TITLE
It should be possible to extends classpath with arbitrary libs

### ISSUE THREAD

**Issue by holgerstolzenberg** [ewerk/gradle-plugins#7]

**Comment by holgerstolzenberg** [comment]
@ilx What do you want to achieve with this. Could you please add some detail on your use case.

**Comment by ilx** [comment]
Classes may contain annotations found in dependencies provided by runtime container (one could use propdeps-plugin for such dependencies) and querydsl annotation processor will fail if it encounters unknown classes (currently the ones outside compile scope).

**Comment by holgerstolzenberg** [comment]
Yeah you are right. Sounds reasonable. I am currently under project load and will be for holidays afterwards. The soonest I will be able to provide that feature is mid of april.

**Comment by holgerstolzenberg** [comment]
Duplicates #6. Closing.
