### ISSUE TITLE
Can add groovy language support?

### ISSUE THREAD

**Issue by btpka3** [ewerk/gradle-plugins#71]
I prefer groovy as develop language than java, but the querydsl-plugin not support groovy compile. Can add support for groovy?

**Comment by btpka3** [comment]
Tried, and give up. Groovy object has extra "metaClass" property,  and found no way to ignored by querydsl-apt.

The following grade config will stop when processing "metaClass":

```groovy
task generateQueryDSL(type: GroovyCompile, group: 'build', description: 'Generates the QueryDSL query types') {

    source = sourceSets.main.groovy
    classpath = configurations.compile + configurations.querydslapt

    groovyOptions.javaAnnotationProcessing = true
    options.compilerArgs << "-proc:only"
    options.compilerArgs << "-processor" << "org.springframework.data.mongodb.repository.support.MongoAnnotationProcessor"

    destinationDir = sourceSets.generated.java.srcDirs.iterator().next()
}
```

**Comment by btpka3** [comment]
"metaClass" related error maybe should be resolved by querydsl. Post an issue:

* querydsl issues [2116](https://github.com/querydsl/querydsl/issues/2116)
* spring-data-mongo issues [1640](https://jira.spring.io/browse/DATAMONGO-1640)

**Comment by holgerstolzenberg** [comment]
Closing this as plugins are not directly designed to support Groovy language.
