### ISSUE TITLE
querydsl-plugin: Default sources directory created even when querydslSourcesDir is set

### ISSUE THREAD

**Issue by robmoore** [ewerk/gradle-plugins#72]
I've set the value to be in another directory but the src/querydsl directory is created nevertheless.

**Comment by griffio** [comment]
Hi, @robmoore
Yes, I take it you are seeing this in Intellij - see http://mrhaki.blogspot.co.uk/2016/03/gradle-goodness-source-sets-as-intellij.html.  The plugin always creates a sourceset called querydsl and Intellij will create a module even if you use a different output directory for your generated sources.

Gradle build itself doesn't create a sourceset folder just using ./gradlew

I was interested if folks are placing generated source under "project build dir" or somewhere else?

If we could make that the default location. The main problem with any solution is getting Intellij to "see" generated source folders, not with Gradle.

Regards, griffo

**Comment by robmoore** [comment]
Indeed, it is when using Intellij. My apologies for not recognizing it as a IDE-specific issue. We do place the files under the build dir. I've noticed other tools generate file in that dir as well.

**Comment by holgerstolzenberg** [comment]
Just to share my thoughts on that: 

I think it is mostly a good idea to places generated sources under the `src` directory of your project, as they are 'sources'. The only difference is that I do not check in generated sources to the repository, as they recreated by the build. That works pretty well so far. I do not see a general reason why to put generated sources to the build dir. Its something I already did in earlier days but then recognising it is not a really good solution. 

It´s just my opinion, do not want to start a real discussion about it here :-)
