### ISSUE TITLE
Is there support for binding files?

### ISSUE THREAD

**Issue by koala421** [ewerk/gradle-plugins#74]
Hello, 

Is there a way you can add binding files to the gradle compilation. For example:

``jaxb2{ xjc{ 'genertor' {gerenatedSourcesDir ="location" basePackage = "com.nav.github" schema = "adsfk.xsd" **Binding=binding.xjb**}}``

**Comment by holgerstolzenberg** [comment]
At the moment the plugin does not support that. As the plugin essentially is a wrapper around Ant XJC task, the task itself needs to support that.

After having a quick look at https://jaxb.java.net/nonav/2.0.2/docs/xjcTask.html, it seems to be possible.

I will try to implemented the feature by this week.

**Comment by holgerstolzenberg** [comment]
@koala421 I have introduced 'bindings' directory param and pushed it to MASTER. Before I officially release the plugin, could you please give it a try on your project with a locally build `SNAPSHOT` of the plugin.

**Comment by koala421** [comment]
I have tried to test this plugin and the bindings param is functioning but I was looking for a way to do single binding files so that I may specify which binding file to use for each of my xsd files

**Comment by holgerstolzenberg** [comment]
Okay I see. You could still achieve this by organizing your source files accordingly, e.g.:

```groovy
'alpha' {
  schema = 'resources/alpha.xsd'
  bindings = 'resources' // alpha related *.xjb here
}

'beta' {
  schema = 'resources/beat.xsd'
  bindings = 'resources' // beta related *.xjb here
}
```

Is that an option for you? But in the end I agree, maybe specifying the concrete bindings files is definitely an option, but is still a bit restricted to the XJC specific task call. Please see following code snippet for explanation:

```groovy
@SuppressWarnings("GroovyUnusedDeclaration")
  @TaskAction
  antXjc() {
    ant.taskdef(
        name: 'xjc',
        classname: project.extensions.jaxb2.taskName,
        classpath: project.configurations.jaxb2.asPath)

    Set<XjcTaskConfig> xjcConfigs = project.extensions.jaxb2.xjc

    for (XjcTaskConfig theConfig : xjcConfigs) {
      def generatedSourcesDirParent = project.file(theConfig.generatedSourcesDir)
      def basePackage = theConfig.basePackage

      // Transform package to directory location to specify depends/produces when multiple schema output to same generatedSourcesDir
      // Changing one schema will only cause recompilation/generation of that schema
      def generatedSourcesDirPackage = new File(generatedSourcesDirParent,
          basePackage.replace(".", "/"))

      def schemaFile = project.file(theConfig.schema)
      def bindings = theConfig.bindings

      // the depends and produces is compared using the time-stamp of the schema file and the destination package folder
      ant.xjc(destdir: generatedSourcesDirParent,
          package: basePackage,
          schema: schemaFile) {
        depends(file: schemaFile)
        produces(dir: generatedSourcesDirPackage, includes: "**/*.java")

        if (bindings?.trim()) {
          binding(dir: project.file(bindings), includes: '**/*.xjb')
        }
      }
    }
  }
```

**Comment by koala421** [comment]
In the binding area it would be nice to have `binding(dir: project.file(bindings), includes: 'project.file(binding1), project.files(binding2)...')` kind of like [This](http://stackoverflow.com/questions/43054081/multiple-binding-files-in-gradle-xjc-task) or [this implementation](https://github.com/IntershopCommunicationsAG/jaxb-gradle-plugin)

**Comment by holgerstolzenberg** [comment]
@koala421 Can you please give it another try. I´ve added support for explicit binding file includes.

**Comment by koala421** [comment]
@holgerstolzenberg Awesome!...It works

**Comment by koala421** [comment]
Is this going to be an official gradle plugin soon with the updates?

**Comment by holgerstolzenberg** [comment]
Plugin version `1.0.4` release and available. Please see:
https://plugins.gradle.org/plugin/com.ewerk.gradle.plugins.jaxb2
