### ISSUE TITLE
Setting gradle sourceSet to generated folder gives the error "The configured generatedSourcesDir must specify a separate location to existing source code"

### ISSUE THREAD

**Issue by tabiul** [ewerk/gradle-plugins#76]
I am trying to configure my gradle so that the generated files are available in the sourceSet so that they are picked up by IntelliJ.
```

jaxb2 {
    xjc {
        'exportRequest' {
            generatedSourcesDir = 'build/generated/main/java'
            basePackage = 'com.test'
            schema = 'src/main/xsd/exportRequest.xsd'
        }
        'exportResponse' {
            generatedSourcesDir = 'build'
            basePackage = 'com.test'
            schema = 'src/main/xsd/exportResponse.xsd'
        }
    }
}


sourceSets {
    main {
        java {
            srcDirs += 'build/generated/main/java'
        }
    }
}
```

Doing this it throws the error "The configured generatedSourcesDir must specify a separate location to existing source code". I can see in the code there is an explicit check for this. I do not get why this check is there. I am also using another plugin https://github.com/google/protobuf-gradle-plugin and that plugin output the generated files to `build` folder and since I setup the `build` folder as part of `srcDir`, the generated classes is available. I am not sure why this cannot be done or maybe there is a workaround.

**Comment by griffio** [comment]
@tabiul

**Comment by tabiul** [comment]
Similar to what the protobuf plugin is doing, generating to build folder. Deleting the sub-directory under build I think should be safe. Furthermore, normally the path specified would be a subdirectory under src so in that sense it is not like the whole directory will be deleted. I can see from where this check is coming from but I think maybe it is not really needed or like you said be bit more specific. Is there a plan to work on this soon ?

**Comment by holgerstolzenberg** [comment]
"The plugins are designed to work from a non build src location" thats the key point here. I am not quite sure if it is senseful to change anything.

@tabiul I´d like to know what your intentions are putting the sources under the `build` directory. The time I started working with code generation, I also though that this would be a good idea. Working with it a bit more I realized that putting them under the `src` directory is a much better approach regarding convention/configuration issues.

Lastly I noticed that there may be an error in the example you provided. Shall the `generatedSourcesDir` for the `exportResponse` stuff really be just `build`? That may flush your whole build dir upon sources generation.

**Comment by tabiul** [comment]
@holgerstolzenberg yes, you are right. It should be `build/generated/main/java` instead of `build`. Actually the one reason for me for asking this one making it easier to work with IntelliJ. I need somehow to tell IntelliJ via Gradle that the source code is there so that it can be used for compilation and code completion. If there is way to do that then there is no need of this change. Maybe I am missing something.

**Comment by holgerstolzenberg** [comment]
For me the most useful way is to generate the sources to somewhere under `src/(main)/jaxb2` or in your case more domain specific like `src/main/export-request`. Then you have all your sources where they should be and IntelliJ will also pick them up. You just need to exclude them from repository check-in via Git/SVN/… ignores.

**Comment by tabiul** [comment]
Thanks @holgerstolzenberg . I will look at the sample.

**Comment by Toby91** [comment]
> For me the most useful way is to generate the sources to somewhere under `src/(main)/jaxb2` or in your case more domain specific like `src/main/export-request`. Then you have all your sources where they should be and IntelliJ will also pick them up automatically. No need to play around with the `sourceSets`. You just need to exclude them from repository check-in via Git/SVN/… ignores.

I don't think this is true. Even if you generate files inside /src/main/xxx IntelliJ does not see them. The one thing that works for me (and I prefere to do it this way) is to generate files inside the build directory and configure this directory as sourceSet. But the plugin will not let you do that. Implementing #124 would be a solution. This just stopping me to do what I really want to do. Even if it works in some Intellij versions, why the plugin should even bother where files are generated?

**Comment by skywangyan** [comment]
> > For me the most useful way is to generate the sources to somewhere under `src/(main)/jaxb2` or in your case more domain specific like `src/main/export-request`. Then you have all your sources where they should be and IntelliJ will also pick them up automatically. No need to play around with the `sourceSets`. You just need to exclude them from repository check-in via Git/SVN/… ignores.
> 
> I don't think this is true. Even if you generate files inside /src/main/xxx IntelliJ does not see them by default. The one thing that works for me (and I prefer to do it this way) is to generate files inside the build directory (similar to maven's target folder and maven jaxb plugin) and configure this directory as sourceSet. But the plugin will not let you do that. Implementing #124 would be a solution. This just stopping me to do what I really want to do. Even if it works in some Intellij versions, why the plugin should even bother where files are generated?

Agree, the location of generated code should not matter, by default it should not be in src/main,
as long as gradle specify where to find the source code,  it should not matter. This is bad, hope to fix.
