### ISSUE TITLE
Change default generated setter method name in builder for AutoValue plugin

### ISSUE THREAD

**Issue by maxTanquerel** [ewerk/gradle-plugins#77]
Hi,
I'd like to be able to change the generated name for set methods in the builder. I am not a groovy dev so I don't understand what I should update to make that change. Can someone help me so that change ?

I'd like set method looks like :
public abstract Builder setUrl(String url); 

Thank you for your help

**Comment by griffio** [comment]
@maxTanquerel, Builders are customised in your own code as you know what convention to use.
I don't know if you found this howto - 
https://github.com/google/auto/blob/master/value/userguide/builders-howto.md#beans

**Comment by maxTanquerel** [comment]
I understand that I have the choice, and I choose to have the set prefix. But when I am using your plugin it without the prefix, how can I add this prefix at the generation ?

**Comment by holgerstolzenberg** [comment]
As I understand the HOWTO you do not need to change anything with the plugin. Just name your setters using the `set` prefix. Auto-Value is capable of handling this as the method signatures for setters do have a parameter. You only have to make sure that **all** setters in your `@AutoValue` Builder class use that prefix.

**Comment by maxTanquerel** [comment]
If I understand well the goal of the plugin is to generate builder, create etc... I was probably not clear but in the builder, this is how I am using the plugin :

I write that :
`@AutoValue
public abstract class Foo {
    public abstract String foo();
}`

the plugin will generate that : 
`@AutoValue
public abstract class Foo {
    public abstract String foo();

    public static Builder builder() {
        return new AutoValue_Foo.Builder();
    }

    @AutoValue.Builder public abstract static class Builder {
        public abstract Builder foo(String foo);
        public abstract Foo build();
    }
}`

I would like it generate that :
`@AutoValue
public abstract class Foo {
    
    public abstract String foo();

    public static Builder builder() {
        return new AutoValue_Foo.Builder();
    }

    @AutoValue.Builder public abstract static class Builder {
        public abstract Builder setFoo(String foo);
        public abstract Foo build();
    }
}`

Is it possible ?

**Comment by holgerstolzenberg** [comment]
Well we already understood what you want to do :-)

At first you need to realise that this plugin is just a wrapper around AutoValue, it triggers it but has nothing to do with how AutoValue actually generates the code.

I have put together a small sample project show casing what you want to achieve:
https://github.com/holgerstolzenberg/autovalue-demo

Hope that finally helps.
