### ISSUE TITLE
Getting java.lang.NullPointerException

### ISSUE THREAD

**Issue by jackmatt2** [ewerk/gradle-plugins#8]
Build script command
```
querydsl {
  library = "com.mysema.querydsl:querydsl-apt:3.6.0"
  querydslSourcesDir = "src/querydsl/java"
  jpa = true
}
```

Error

```
09:26:09.468 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':bom:bom-web:compileQuerydsl'
09:26:09.468 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :bom:bom-web:compileQuerydsl FAILED
09:26:09.468 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :bom:bom-web:compileQuerydsl (Thread[main,5,main]) completed. Took 2.349 secs.
09:26:09.469 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 4.904 secs, idle: 0.006 secs
09:26:09.473 [ERROR] [org.gradle.BuildExceptionReporter] 
09:26:09.473 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
09:26:09.474 [ERROR] [org.gradle.BuildExceptionReporter] 
09:26:09.474 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
09:26:09.474 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':bom:bom-web:compileQuerydsl'.
09:26:09.474 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.NullPointerException
09:26:09.474 [ERROR] [org.gradle.BuildExceptionReporter] 
09:26:09.474 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
09:26:09.475 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
09:26:09.475 [LIFECYCLE] [org.gradle.BuildResultLogger] 
09:26:09.475 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
```

Any ideas why this might be?  I can see that the queryDSL objects have been created in the /main/queryDsl/java folder.  I have tried with --debug but it does not tell me what entity is causing the issue.

**Comment by jackmatt2** [comment]
I found the issue. 

All my domain objects extend a BasicDomainObject class.  This class is in a separate project "common-code" as it is shared with a number of different projects.  It seems that the generator can't find this class and thinks it does not exist.

Do you know of a solution?

**Comment by holgerstolzenberg** [comment]
Hm seems like this might be an issue how the plugin utilises the classpath of the project. It would be great if you could provide a sample project illustrating the issue.

Still due to holidays, I won´t be able to investigate this before Mid of april.

**Comment by jackmatt2** [comment]
I can't give you the exact project but I will try to reproduce in a demo.

**Comment by holgerstolzenberg** [comment]
Hey @jackmatt2, do you have a sample project available?

**Comment by jackmatt2** [comment]
I still need to do one.

**Comment by jackmatt2** [comment]
@holgerstolzenberg I have been trying to reproduce this at home but it is working ...

**Comment by holgerstolzenberg** [comment]
So then I will close that for now. If you have any troubles come back again.
