### ISSUE TITLE
QueryDsl compile kotlin

### ISSUE THREAD

**Issue by bastman** [ewerk/gradle-plugins#80]
Hi, I'm just wondering if you could provide an example for this kind of setup:

- kotlin
- gradle
- spring-boot 1.5.*, jpa, hibernate

Thanks a lot for your help.

/Seb

**Comment by griffio** [comment]
@bastman great you are a fan of Kotlin!

Typically for Kotlin, we have to use kapt directly -> see here for https://github.com/griffio/dagger2-kotlin/blob/master/build.gradle example.

The plugins developed in this gradle-plugins project are based around the javac annotation processor so are not Kotlin applicable.
