### ISSUE TITLE
QueryDsl for a java and groovy project

### ISSUE THREAD

**Issue by tabiul** [ewerk/gradle-plugins#83]
I have a project that has mix of both Java and Groovy. As I understand the plugin does not support Groovy domain model file as such I moved all domain model to  Java. In order to make the compilation work I followed this https://stackoverflow.com/questions/22159699/gradle-groovy-and-java-class-dependency-compile. The task `compileGroovy` works fine as the Java entity model references some class in Groovy. The problem is that for some reason the querydsl auto generated files are not being generated. I think `compileJava` is not being called. Manually calling `compileJava` gives

> * What went wrong:
Circular dependency between the following tasks:
:compileQuerydsl
\--- :compileQuerydsl (*)
(*) - details omitted (listed previously) 

I tried this `tasks.getByPath('compileQuerydsl').mustRunAfter compileGroovy` and then does not work. So I need to somehow trigger `compileJava` I think.

```
sourceSets {
    main {
        groovy {
            srcDirs = ['src/main/groovy', 'src/main/java']
        }
        java {
            srcDirs = []
        }
    }

    test {
        groovy {
            srcDirs = ['test/main/groovy']
        }
    }
}

// remove GroovyCompile->JavaCompile task dependencies
tasks.withType(GroovyCompile) {
    dependsOn = []
}

// add JavaCompile->GroovyCompile task dependencies
tasks.withType(JavaCompile) { task ->
    dependsOn task.name.replace("Java", "Groovy")
}

def querydslDir = 'build/classes/main/generated'

querydsl {
    jpa = true
    querydslSourcesDir = querydslDir

}

idea {
    module {
        sourceDirs += file(querydslDir)
    }
}
```

**Comment by holgerstolzenberg** [comment]
Closing this as plugins are not directly designed to support Groovy language.
