### ISSUE TITLE
Missing automatic Gradle dependency

### ISSUE THREAD

**Issue by andilem** [ewerk/gradle-plugins#85]
The dependency
`'org.jvnet.jaxb2_commons:jaxb2-basics-tools:' + JAXB2_VERSION` is missing in Jaxb2Plugin.groovy line 85-87.
This artifact contains the class AbstractParameterizablePlugin which cannot be found at the moment.
This artifact needs the dependency commons-logging:commons-logging:1.2 which also must be included.

So at the moment, for me it's necessary to add the two
```
dependencies {
    jaxb2 'org.jvnet.jaxb2_commons:jaxb2-basics-tools:0.9.5'
    jaxb2 'commons-logging:commons-logging:1.2'
}
```

**Comment by holgerstolzenberg** [comment]
I am struggling with a definite solution here. Sure I can add these lines without a problem, but:

- This issue occurred for the first time having the plugin out there for a while, it seems your jaxb2 usage does something specific not bugging others
- Making the plugin manage the `jaxb2-basics-tools` dependency means also adding `commons-logging`

It might not be the best choice to make the plugin directly dependent to `commons-logging`. The workaround you provide is very straightforward.

@andilem Do you really see it as a necessary addition to the plugin itself?

**Comment by andilem** [comment]
I don't think I am doing something specific, I'm just creating Java classes from an XSD in the most simple way, no special options. I'm wondering that noone else has this problem.
The stacktrace is
```
java.lang.NoClassDefFoundError: org/jvnet/jaxb2_commons/plugin/AbstractParameterizablePlugin
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:116)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.nodeCompleted(BasicAntBuilder.java:78)
        at org.gradle.api.internal.project.ant.BasicAntBuilder.doInvokeMethod(BasicAntBuilder.java:103)
        at com.ewerk.gradle.plugins.tasks.GenerateJaxb2Classes.antXjc(GenerateJaxb2Classes.groovy:52)
```
but I'm unfortunately not familiar with the jaxb2_commons stuff.
If you cannot reproduce this issue (I can) and don't want to include the dependency, perhaps it's worth mentioning this problem (and the solution) in the readme.md file for the case that someone else stumbles over this.

**Comment by holgerstolzenberg** [comment]
I have added the dependencies to the plugin and released it.

https://plugins.gradle.org/plugin/com.ewerk.gradle.plugins.jaxb2
