### ISSUE TITLE
Failing master build due to Travis Android config

### ISSUE THREAD

**Issue by holgerstolzenberg** [ewerk/gradle-plugins#86]
Master build is broken. It looks like Android config is not up to date.

Please see:
https://docs.travis-ci.com/user/languages/android/

**Comment by holgerstolzenberg** [comment]
@griffio Could you have a look at that?

**Comment by griffio** [comment]
Hi - yes 
Should be able to look at today or evening.
Hopefully - it's simple as
> No build-tools version is specified in android.components. Consider adding one of: build-tools-27.0.1

**Comment by holgerstolzenberg** [comment]
I´ve really overlooked that one. I tried to fix it according to Travis docs but keep struggling with the license acceptance. I do not have the time to dig deeper into it. The following help might provide some useful information about that.

https://developer.android.com/studio/intro/update.html#download-with-gradle

**Comment by griffio** [comment]
Yep - looks like the versions defined in travis have to match the ones defined in gradle 
Having done so - there is now another runtime error to do with missing method.
-- java.lang.NoSuchMethodError: com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir

Closer...I will see if I can match that version up

gradle build
```
 project.android {
      compileSdkVersion "android-21"
      buildToolsVersion "21.1.2"
      defaultConfig {
        testApplicationId "com.ewerk.gradle.plugins"
        minSdkVersion 15
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
      }
    }
```
