### ISSUE TITLE
Jaxb2 plugin to support extension mode

### ISSUE THREAD

**Issue by rbalazsi** [ewerk/gradle-plugins#89]
I configured my bindings so the generated sources would implement Serializable, i.e.:
```
<jxb:bindings version="2.1"
              xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
              xmlns:xs="http://www.w3.org/2001/XMLSchema"
              xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc">

    <jxb:globalBindings>
        <xjc:serializable/>
    </jxb:globalBindings>

    <jxb:bindings schemaLocation="my-data.xsd" node="/xs:schema">
        <jxb:schemaBindings>
            <jxb:package name="my.package"/>
        </jxb:schemaBindings>
    </jxb:bindings>
</jxb:bindings>
```

However, I'm now getting the following error:

> [ERROR] vendor extension bindings (jaxb:extensionBindingPrefixes) are not allowed in the strict mode. Use -extension.

I see no way to turn off strict mode, please advise.

**Comment by holgerstolzenberg** [comment]
I have added an `extension` config option and updated the docs. The code is already on master. The reference docs I used were: https://javaee.github.io/jaxb-v2/doc/user-guide/ch04.html

I have not time to try this out or write some distinctive tests for that. Could you please try the current snapshot locally. If all works fine, I´ll release the plugin to the portal.

**Comment by holgerstolzenberg** [comment]
Ping @rbalazsi any news, otherwise I am going to release the plugin and close the issue.

**Comment by holgerstolzenberg** [comment]
Plugin was released:

https://plugins.gradle.org/plugin/com.ewerk.gradle.plugins.jaxb2
