### ISSUE TITLE
Is it possible to create Q-classes from classpath using querydsl-plugin?

### ISSUE THREAD

**Issue by persapiens** [ewerk/gradle-plugins#91]
Hi, I use this plugin to create jpa Q-classes successfully from java source files located inside the project.

However, is it possible to use this plugin to create jpa Q-classes if compiled entity classes are inside classpath jar libraries? [maven](http://www.querydsl.com/static/querydsl/4.1.4/reference/html/ch03s03.html#d0e2512) has some solution to this. There is a generic approach described [here](http://www.querydsl.com/static/querydsl/4.1.4/reference/html/ch03s03.html#d0e2512).

**Comment by holgerstolzenberg** [comment]
I do not think this is possible. I even do not see the use case. If the library has annotated classes inside, the Q-classes should also be contained. The build process of the library should take care of building the Q-classes, I see no downside to that. Then just integrate the library.
