### ISSUE TITLE
Eclipse output folder confusion

### ISSUE THREAD

**Issue by ben-manes** [ewerk/gradle-plugins#92]
This may be a Buildship problem, but is an issue I encountered recently. The output folder for Eclipse confuses it when trying to run the application. All other source / generated-sources are placed in `bin/main`, but `autoValue` is in `bin/autoValue`. The editor discovers the code, but a `NoClassDefFoundError` occurs when executing it. The solution is to edit the configuration and set it to `bin/main` and the project runs. This all works properly at command-line, though.

I suspect this has something to do with the [autoValue sourceSet](https://github.com/ewerk/gradle-plugins/blob/master/auto-value-plugin/src/main/groovy/com/ewerk/gradle/plugins/AutoValuePlugin.groovy#L88) instead of using `main`, causing Eclipse to mis-associate the output folder.

<img width="1764" alt="screen shot 2018-02-01 at 1 33 55 pm" src="https://user-images.githubusercontent.com/378614/35704519-a6290400-0754-11e8-8764-a9ed4c31e41f.png">

**Comment by holgerstolzenberg** [comment]
Well it is hard to tell what is going on here because I don´t use Eclipse nor Buildship and especially because I do not know your build configuration.
One thing I´d like to emphasize is that I do not think its a good idea to put generated sources to the `bin` or `build` or whatever output folder. Generated sources should also be placed under the source tree of the project/modules. This was the initial design goal of the plugin. Having the generated sources in the output folders makes no sense to me.

**Comment by ben-manes** [comment]
Buildship is built into Eclipse, and sponsored by the Gradle team. The `bin` directory is where Eclipse stores its incrementally compiled output, so as to not conflict with the build tool's.

The more common idiom is that anything generated by the build system goes into its output directory, `build` in Gradle. This would follow other build tools, like Maven and Bazel, and best practices in non-opinionated ones like Ant. If the sources are generated by an external tool not run by the build, then they go in with the sources. However, that is frowned upon because someone may edit it, diff bloat on re-gen, and codegen should not be a performance issue. While you might disagree with the past best practices, places the code under `build` is a common practice.

The configuration is simple. Likely the fix for now will be to add the `autoValue` source dir into the main's.

```gradle
apply plugin: 'com.ewerk.gradle.plugins.auto-value'

def autoValueBaseDir = "${buildDir}/generated-sources/autoValue/"
def autoValueTestSourcesDir = "${autoValueBaseDir}/test"

sourceSets.test.java.srcDirs += autoValueTestSourcesDir
compileTestJava.options.compilerArgs += ['-s', autoValueTestSourcesDir]

autoValue {
  library = libraries.auto_value
  autoValueSourcesDir = "${autoValueBaseDir}/main"
}

dependencies {
  compileOnly libraries.auto_value_builder
}
```

**Comment by ben-manes** [comment]
Closing as I ended up rewriting my build snippet to use `annotationProcessor` and not rely on this plugin. That fixed the odd Eclipse problem, and also let me upgrade to autoValue 1.6. Thanks for the plugin though, it had been helpful.
