### ISSUE TITLE
Generating Q classes from test sources

### ISSUE THREAD

**Issue by pawel-piatkowski** [ewerk/gradle-plugins#94]
Should this plugin generate **Q classes** from test sources i.e **src/test/java**?

**Comment by holgerstolzenberg** [comment]
I never tried that. The plugin is not designed for that use case.
Could you describe your use case with more details? I´d like to know if this is something really needed to be delivered by the plugin.

**Comment by pawel-piatkowski** [comment]
The use case is very fundamental, just imagine you have some generic piece of code and you want to write some integration tests with some example Q classes. In the application I'm currently developing there are plenty of such tests.

**Comment by holgerstolzenberg** [comment]
Actually the plugin was not designed to generated Q classes for tests. This would imply setting up a seconds target folder, e.g. `src/test/querydsl` and adding that to the classpath.

I still don´t really get the point with the example Q classes. A mean "normally" you have Q classes in your `main` source set which are then tested by tests. If it is for demonstration purposes only, I´d consider some kind of separate sample application to showcase the usage of your Q classes from root project.
