### ISSUE TITLE
Pass additional args to xjc (jaxb2 plugin)

### ISSUE THREAD

**Issue by DanAngelus** [ewerk/gradle-plugins#95]
Hi,

Is there a way I can pass additional arguments to xjc such as -XtoString using this plugin?

Regards,
Dan

**Comment by holgerstolzenberg** [comment]
No that is not possible at the moment. 

In general it is possible for the plugin to support more options but that depends upon the options the Ant task provides, which is wrapped by the plugin.

Reading through https://docs.oracle.com/cd/E17802_01/webservices/webservices/docs/2.0/jaxb/xjcTask.html it looks like command line args should be possible.

**Comment by DanAngelus** [comment]
Reading through that page it looks like the 'arg' option is what I need to pass through the additional args, something like this would be useful:
```
jaxb2 {
    xjc {
        'base-schema-output' {
            basePackage = 'com.example.schema'
            schema = 'src/main/resources/xsd/my-schema.xsd'
            bindingsDir = 'src/main/resources/xjb'
            includedBindingFiles = 'bindings.xjb'
            extension = true
            args = ['-XtoString']
        }
    }
}
```

**Comment by holgerstolzenberg** [comment]
Okay I´ll try to get that in place this week.

**Comment by holgerstolzenberg** [comment]
Okay I´ve just released the plugin with the new configuration option `additionalArgs = ['-XtoString']`.

The plugin is available here:
https://plugins.gradle.org/plugin/com.ewerk.gradle.plugins.jaxb2

@DanAngelus could you please give it a try?

**Comment by DanAngelus** [comment]
I've given that a quick test but it doesn't seem to work:

**build.gradle**
```
jaxb2 {
    xjc {
        'base-schema-output' {
            basePackage = 'com.example.schema'
            schema = 'src/main/resources/xsd/my-schema.xsd'
            bindingsDir = 'src/main/resources/xjb'
            includedBindingFiles = 'bindings.xjb'
            extension = true
            additionalArgs = ['-XtoString']
        }
    }
}
```
**my-schema.xsd**
```
<?xml version="1.0"?>
<xs:schema targetNamespace="http://www.example.com/schema"
           attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           jaxb:extensionBindingPrefixes="basic toString"
           xmlns:tns="http://www.example.com/schema"
           xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
           xmlns:basic="http://jaxb2-commons.dev.java.net/basic"
           xmlns:toString="http://jaxb2-commons.dev.java.net/basic/toString"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="MyEntity">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="entityId"/>
        <xs:element type="xs:string" name="description"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

Gives me this error, which seems to indicate that the '-XtoString' argument isn't making it through:
```
>Task :generateJaxb2Classes
[ant:xjc] [ERROR] Using "http://jaxb2-commons.dev.java.net/basic" customizations requires the "-XtoString" switch to enable this plug-in.
[ant:xjc]   line 10 of file:/D:/Projects/jaxb-plugin-test/src/main/resources/xsd/my-schema.xsd
[ant:xjc]
[ant:xjc] [ERROR] Using "http://jaxb2-commons.dev.java.net/basic/toString" customizations requires the "-XtoString" switch to enable this plug-in.
[ant:xjc]   line 10 of file:/D:/Projects/jaxb-plugin-test/src/main/resources/xsd/my-schema.xsd
[ant:xjc]
```

**Comment by boris-petrov** [comment]
@holgerstolzenberg - this doesn't seem to work in my case either. I think the problem is [here](https://github.com/ewerk/gradle-plugins/commit/9d5c3187415dcbb417090edc18f980dca6378fb1#diff-5986af2a9a23367ac51181535acac4adR19). The `arg` argument is expected to be a string of arguments according to the documentation (as you have also written in the README) but you've actually made it a Set. Changing this to `String` should resolve the issue I think.
