### ISSUE TITLE
Querydsl : Add support for querydsl compiler args

### ISSUE THREAD

**Issue by alvinmeimoun** [ewerk/gradle-plugins#97]
Hi

The Maven QueryDSL plugin has possibility to add some custom parameters to the QueryDSL compiler. When i migrated my project to Gradle, i tried to find the same on this plugin but it doesn't seem available.

This is the Maven plugin configuration that contains the parameters
```
<options>
<querydsl.entityAccessors>true</querydsl.entityAccessors>
<querydsl.useFields>false</querydsl.useFields>
</options>
```

They change the way that QueryDSL are generated.

I found a workaround without using the plugin but i needed to override the generateSources task ans manually manage generation. That is the goal of this plugin

```
options.compilerArgs = ['-proc:only',
                           '-processor',  
                           'com.querydsl.apt.jpa.JPAAnnotationProcessor',  
                           '-Aquerydsl.entityAccessors=true',  
                           '-Aquerydsl.useFields=false']
```

I suggest to add these two parameters to this gradle plugin configuration.
I also suggest to add a parameter that allow custom args for the compiler

Like : 
```
querydsl {
  useFields=false  
  entityAccessors=true  
}
```

```
querydsl {  
  customArgs=['querydsl.entityAccessors=true','querydsl.useFields=false']  
}
```

I think this issue can be labelled as feature request

**Comment by griffio** [comment]
Hi @alvinmeimoun - I think the plugin can support the apt global serializer configuration _better_. The serializer _annotations_ placed in code only support a limited number of options.
Also, the list of compiler options changes per release...
Currently http://www.querydsl.com/static/querydsl/4.2.1/reference/html/ch03s03.html
So the way it is configured in the plugin needs to support that. 

If you feel like you can create a :octocat: Pull Request for this then please do.  
📆 I will have some time by the end of next week

**Comment by alvinmeimoun** [comment]
Hi,

I made a pull request

As you said i agree that it's difficult to make a correct list of options due to the changes per release.
So i just added a parameter name aptOptions (List) and these paramaters are passed as compiler agrs prefixed by "-A". It let the flexibility of APT parameters for any release of querydsl

**Comment by griffio** [comment]
@alvinmeimoun Thanks - I was able to try it out locally on the latest gradle 4.7 and seems ok
@holgerstolzenberg Can you take a look at this PR and see if it can make it to release?

**Comment by holgerstolzenberg** [comment]
Sorry guys, have been very busy lately and my Github notifications messed up, otherwise the PR would have had it made to release much earlier.

@alvinmeimoun Thanks for the PR.

Plugin with version `1.0.10` was released to the portal.
